<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $block \Amasty\GiftCard\Block\Checkout\Cart\GiftCard */ ?>
<?php if ($block->isEnableGiftFormInCart()): ?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?php echo __('Apply Gift Card Code') ?></strong>
    </div>

    <div class="content" data-role="content" aria-labelledby="block-discount-heading">

        <div id="amgiftcard_info"></div>

        <?php $getAppliedCodes = $block->getAppliedCodes(); ?>
        <?php if(count($getAppliedCodes)): ?>
            <div class="codes-list">
                <?php foreach ($getAppliedCodes as $code): ?>
                    <div>
                        <?php echo $code->getCode();?>
                        <a class="btn-remove btn-remove-amgiftcard" href="<?php echo $block->getUrl('amgiftcard/cart/remove', ['code_id' => $code->getCodeId()]);?>" title="Remove">
                            <?php echo __('Remove'); ?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>

        <?php endif;?>

        <form id="amgiftcard-form"
              action="<?php echo $block->getUrl('amgiftcard/cart/apply') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code" class="label"><span><?php echo __('Enter gift card code') ?></span></label>
                    <div class="control">
                        <input class="input-text" type="text" id="am_giftcard_code" name="am_giftcard_code" value=""  placeholder="<?php echo $block->escapeHtml(__('Enter gift card code'));?>"/>
                    </div>
                </div>
            </div>
            <div class="amactions-toolbar">
                <button class="action apply primary" type="submit" value="<?php echo __('Add Gift Card') ?>">
                    <span><?php echo __('Add Gift Card') ?></span>
                </button>

                <button type="button" id="amgiftcard_check_status" class="action primary" value="<?php echo __('Check Gift Card status') ?>">
                    <span><?php echo __('Check Gift Card status') ?></span>
                </button>

            </div>

            <script>
                require([
                    'jquery',
                    'Amasty_GiftCard/js/cart/main'
                ], function ($) {
                    $('#amgiftcard_check_status').amGiftcardCart({
                        checkCardUrl: "<?php echo $block->getUrl('amgiftcard/cart/check') ?>"
                    });
                });

            </script>
        </form>
    </div>
</div>
<?php endif;?>