<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/blog/the-pea-coat-a-seafaring-staple/"> <img src="{{media url='wysiwyg/menublock-images/blog_1_1.jpg'}}" alt="The Pora Coat Uncovered" /> </a></figure>
    <figure><a href="/blog/suit-fit-guide/"> <img src="{{media url='wysiwyg/menublock-images/blog_2_1.jpg'}}" alt="Our Suit Fit Guide" /> </a></figure>
    <figure><a href="/blog/3-key-pieces-power-winter-tailoring/"> <img src="{{media url='wysiwyg/menublock-images/blog_3_4.jpg'}}" alt="3 Key Winter Pieces" /> </a></figure>
</section>