<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$categoryImage = $block->getCurrentCategory()->getImageUrl();
?>

<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description catalog-main__description <?php if($categoryImage):?>has-image<?php endif;?>">
        <div class="catalog-main__description--left-column">
            <a href="/" class="catalog-main__description--back"></a>
            <?php
            $categoryImage = $block->getCurrentCategory()->getImageUrl();

            if($categoryImage): ?>
            <div class="catalog-main__image">
                <img src="<?php echo $block->getCurrentCategory()->getImageUrl(); ?>" />
            </div>
            <?php endif; ?>

        </div>
        <div class="catalog-main__description--right-column <?php if(!$categoryImage):?>text-center<?php else: ?>image-on-left<?php endif;?>">
            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
        </div>
    </div>
<?php endif; ?>
