<?php
/**
 * Category sidebar
 *
 * @var $block PandaGroup\CategorySidebar\Block\Sidebar
 */
$categories = $block->getCategories();
$brands = $block->getBrands();
?>
<ul class="o-list">
    <?php
    /** @var \Magento\Catalog\Model\Category $category */
    foreach ( $categories as $category ) :
        ?>
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
            <div class="layered-nav__title filter-options-title">
                <span><?php echo __('Category'); ?></span>
            <?php if ( $category->hasChildren() ) : ?>
                <span class="expand">
                    <?php echo $block->isActive($category) ? '<figure class="layered-nav__minus layered-nav__minus--plus">
                            <span class="layered-nav__line layered-nav__line--horizontal"></span>
                            <span class="layered-nav__line layered-nav__line--vertical"></span>
                        </figure>' : '<figure class="layered-nav__minus">
                            <span class="layered-nav__line layered-nav__line--horizontal"></span>
                            <span class="layered-nav__line layered-nav__line--vertical"></span>
                        </figure>'; ?>
                </span>
            <?php endif; ?>
            </div>

            <?php echo $block->getChildCategoryView($category); ?>
        </li>
    <?php endforeach; ?>
</ul>
