<div class="storelocator" id="preact-root"></div>


<script type="text/javascript">

    var data_json =
        {
            "constants": {
                "apiKey": "AIzaSyAyesbQMyKVVbBgKVi2g6VX7mop2z96jBo",
                "geo": { "lat": 52.4046, "lng": 16.9252 },
                "zoom": 7,
                "country": "au",
                "pin": "http://www.peterjacksons.com/media/storelocator/images/icon/pinpj2.png"
            },
            "regions": [
                {
                    "name": "VIC",
                    "geo": { "lat": 37.078873, "lng": -111.253838 },
                    "zoom": 9
                },
                {
                    "name": "SA",
                    "geo": { "lat": 38.953524, "lng": -117.101054 },
                    "zoom": 9
                },
                {
                    "name": "QLD",
                    "geo": { "lat": 64.251461, "lng": -18.904957 },
                    "zoom": 9
                },
                {
                    "name": "NSW",
                    "geo": { "lat": 58.4046, "lng": -46.9252 },
                    "zoom": 9
                },
                {
                    "name": "ACT",
                    "geo": { "lat": 48.4046, "lng": -56.9252 },
                    "zoom": 9
                }
            ],
            "stores": [
                {
                    "name": "Head office",
                    "id": "head-office",
                    "addr_strt": "426 Johnston Street, Abbotsford",
                    "addr_cty": "Melbourne Victoria 3000",
                    "geo": { "lat": 58.4046, "lng": 16.9252 },
                    "zoom": 17,
                    "phone": "666 666 666",
                    "email": "info@peterjacksons.com",
                    "region": "QLD",
                    "hours": {
                        "SUN": [
                            "Closed",
                            "Closed"
                        ],
                        "MON": [
                            "9:00 AM",
                            "5:30 PM"
                        ],
                        "TUE": [
                            "9:00 AM",
                            "5:00 PM"
                        ],
                        "WED": [
                            "9:30 AM",
                            "5:10 PM"
                        ],
                        "THU": [
                            "9:34 AM",
                            "5:20 PM"
                        ],
                        "FRI": [
                            "10:34 AM",
                            "11:20 PM"
                        ],
                        "SAT": [
                            "Closed",
                            "Closed"
                        ]
                    }
                },
                {
                    "name": "EMPORIUM",
                    "id": "emporium",
                    "addr_strt": "Emporium Melbourne , 295 Lonsdale Street",
                    "addr_cty": "Melbourne 3000",
                    "geo": { "lat": 46.4046, "lng": 16.9252 },
                    "zoom": 9,
                    "phone": "777 777 777",
                    "email": "emporium@peterjacksons.com",
                    "region": "SA",
                    "hours": {
                        "SUN": [
                            "8:00 AM",
                            "11:20 PM"
                        ],
                        "MON": [
                            "3:00 AM",
                            "5:30 PM"
                        ],
                        "TUE": [
                            "3:00 AM",
                            "5:00 PM"
                        ],
                        "WED": [
                            "3:30 AM",
                            "5:10 PM"
                        ],
                        "THU": [
                            "3:34 AM",
                            "5:20 PM"
                        ],
                        "FRI": [
                            "3:34 AM",
                            "11:20 PM"
                        ],
                        "SAT": [
                            "Closed",
                            "Closed"
                        ]
                    }
                },
                {
                    "name": "BOURKE ST",
                    "id": "bourke-st",
                    "addr_strt": "420 Bourke St",
                    "addr_cty": "Melbourne 3000",
                    "geo": { "lat": 34.4046, "lng": 16.9252 },
                    "zoom": 9,
                    "phone": "111 111 111",
                    "email": "bourke@peterjacksons.com",
                    "region": "QLD",
                    "hours": {
                        "SUN": [
                            "9:00 AM",
                            "11:50 AM"
                        ],
                        "MON": [
                            "4:00 AM",
                            "5:30 PM"
                        ],
                        "TUE": [
                            "1:00 AM",
                            "2:00 PM"
                        ],
                        "WED": [
                            "3:30 AM",
                            "4:10 PM"
                        ],
                        "THU": [
                            "5:34 AM",
                            "6:20 PM"
                        ],
                        "FRI": [
                            "17:34 AM",
                            "14:20 PM"
                        ],
                        "SAT": [
                            "17:34 AM",
                            "14:20 PM"
                        ]
                    }
                },
                {
                    "name": "BOURKE ST 2",
                    "id": "bourke-st-2",
                    "addr_strt": "420 Bourke St 2",
                    "addr_cty": "Melbourne 3000 2",
                    "geo": { "lat": 21.4046, "lng": 16.9252 },
                    "zoom": 9,
                    "phone": "111 111 111 2",
                    "email": "bourke@peterjacksons.com 2",
                    "region": "SA",
                    "hours": {
                        "SUN": [
                            "9:00 AM",
                            "11:50 AM"
                        ],
                        "MON": [
                            "4:00 AM",
                            "5:30 PM"
                        ],
                        "TUE": [
                            "1:00 AM",
                            "2:00 PM"
                        ],
                        "WED": [
                            "3:30 AM",
                            "4:10 PM"
                        ],
                        "THU": [
                            "5:34 AM",
                            "6:20 PM"
                        ],
                        "FRI": [
                            "17:34 AM",
                            "14:20 PM"
                        ],
                        "SAT": [
                            "17:34 AM",
                            "14:20 PM"
                        ]
                    }
                }
            ]
        };


    require(['store-locator'], function(StoreLocator) {
        StoreLocator.init(data_json);
    });
</script>
