<div id="preact-root"></div>


<script type="text/javascript">

    var data_json =
    {
        "constants": {
            "geo": { "lat": 52.4046, "lng": 16.9252 },
            "zoom": 7
        },
        "regions": [
            {
                "name": "VIC",
                "geo": { "lat": 37.078873, "lng": -111.253838 },
                "zoom": 9
            },
            {
                "name": "SA",
                "geo": { "lat": 38.953524, "lng": -117.101054 },
                "zoom": 9
            },
            {
                "name": "QLD",
                "geo": { "lat": 64.251461, "lng": -18.904957 },
                "zoom": 9
            },
            {
                "name": "NSW",
                "geo": { "lat": 58.4046, "lng": -46.9252 },
                "zoom": 9
            },
            {
                "name": "ACT",
                "geo": { "lat": 48.4046, "lng": -56.9252 },
                "zoom": 9
            }
        ],
        "stores": [
            {
                "name": "Head office",
                "addr-strt": "426 Johnston Street, Abbotsford",
                "addr-cty": "Melbourne Victoria 3000",
                "geo": [],
                "phone": "666 666 666",
                "email": "info@peterjacksons.com",
                "region": "QLD",
                "hours": {
                    "SUN": [
                        "Closed",
                        "Closed"
                    ],
                    "MON": [
                        "9:00 AM",
                        "5:30 PM"
                    ],
                    "TUE": [
                        "9:00 AM",
                        "5:00 PM"
                    ],
                    "WED": [
                        "9:30 AM",
                        "5:10 PM"
                    ],
                    "THU": [
                        "9:34 AM",
                        "5:20 PM"
                    ],
                    "FRI": [
                        "10:34 AM",
                        "11:20 PM"
                    ],
                    "SAT": [
                        "Closed",
                        "Closed"
                    ]
                }
            },
            {
                "name": "EMPORIUM",
                "addr-strt": "Emporium Melbourne , 295 Lonsdale Street",
                "addr-cty": "Melbourne 3000",
                "geo": [],
                "phone": "777 777 777",
                "email": "emporium@peterjacksons.com",
                "region": "SA",
                "hours": {
                    "SUN": [
                        "8:00 AM",
                        "11:20 PM"
                    ],
                    "MON": [
                        "3:00 AM",
                        "5:30 PM"
                    ],
                    "TUE": [
                        "3:00 AM",
                        "5:00 PM"
                    ],
                    "WED": [
                        "3:30 AM",
                        "5:10 PM"
                    ],
                    "THU": [
                        "3:34 AM",
                        "5:20 PM"
                    ],
                    "FRI": [
                        "3:34 AM",
                        "11:20 PM"
                    ],
                    "SAT": [
                        "Closed",
                        "Closed"
                    ]
                }
            },
            {
                "name": "BOURKE ST",
                "addr-strt": "420 Bourke St",
                "addr-cty": "Melbourne 3000",
                "geo": [],
                "phone": "111 111 111",
                "email": "bourke@peterjacksons.com",
                "region": "QLD",
                "hours": {
                    "SUN": [
                        "9:00 AM",
                        "11:50 AM"
                    ],
                    "MON": [
                        "4:00 AM",
                        "5:30 PM"
                    ],
                    "TUE": [
                        "1:00 AM",
                        "2:00 PM"
                    ],
                    "WED": [
                        "3:30 AM",
                        "4:10 PM"
                    ],
                    "THU": [
                        "5:34 AM",
                        "6:20 PM"
                    ],
                    "FRI": [
                        "17:34 AM",
                        "14:20 PM"
                    ],
                    "SAT": [
                        "17:34 AM",
                        "14:20 PM"
                    ]
                }
            },
            {
                "name": "BOURKE ST 2",
                "addr-strt": "420 Bourke St 2",
                "addr-cty": "Melbourne 3000 2",
                "geo": [],
                "phone": "111 111 111 2",
                "email": "bourke@peterjacksons.com 2",
                "region": "SA",
                "hours": {
                    "SUN": [
                        "9:00 AM",
                        "11:50 AM"
                    ],
                    "MON": [
                        "4:00 AM",
                        "5:30 PM"
                    ],
                    "TUE": [
                        "1:00 AM",
                        "2:00 PM"
                    ],
                    "WED": [
                        "3:30 AM",
                        "4:10 PM"
                    ],
                    "THU": [
                        "5:34 AM",
                        "6:20 PM"
                    ],
                    "FRI": [
                        "17:34 AM",
                        "14:20 PM"
                    ],
                    "SAT": [
                        "17:34 AM",
                        "14:20 PM"
                    ]
                }
            }
        ]
    };


    require(['store-locator'], function(StoreLocator) {
        StoreLocator.init(data_json);
    });
</script>