<?php
$objectManagerCms = \Magento\Framework\App\ObjectManager::getInstance();
$cmsPage = $objectManagerCms->get('\Magento\Cms\Model\Page');
?>
<div class="about-block">
    <div class="about-block__image"><img src='<?php echo $block->getUrl("pub/media/wysiwyg/") . $this->getData('img_path'); ?>'></div>
    <?php if ($this->getData('iframe_code')):?>
        <div class="about-block__video">
            <?php echo $this->getData('iframe_code'); ?>
        </div>
        <div class="about-block__video about-block__video-shadow"></div>
    <?php endif; ?>
    <div class="about-block__text">
        <h1><?php echo $this->getData('img_text'); ?></h1>
        <span><?php echo $this->getData('img_small_text'); ?></span>
    </div>
</div>

<ul class="<? echo $cmsPage->getIdentifier(); ?>">
    <?php /* @escapeNotVerified */ echo $block->getText(); ?>
</ul>

