<?php

$_product = $block->getProduct();
$productUrl = $_product->getProductUrl();

?>

<div class="amasty-quickview-ajax-view__footer">
    <div class="amasty-quickview-ajax-view__goto-product">
        <a href="<?php echo $productUrl ?>">
            View full details
        </a>
    </div>
</div>

<script>
    /**
     * fix to calculate proper size of Quickview fancybox
     */
    require(['jquery'], function($){
        $(window).on("load", function() {
            window.parent.jQuery(window.parent).trigger('resize');
        })
    });
</script>