<?php
$objectManagerCms = \Magento\Framework\App\ObjectManager::getInstance();
$cmsPage = $objectManagerCms->get('\Magento\Cms\Model\Page');
?>
<div class="youtube-player">
<div class="youtube-player__placeholder">
    <div class="youtube-player__img">
        <img src='<?php echo $block->getUrl("pub/media/wysiwyg/") . $this->getData('img_path'); ?>'>
    </div>
    <div class="youtube-player__play-img">
        <img src='<?php echo $block->getUrl("pub/media/wysiwyg/") . 'about-us/video-play.png'; ?>' alt="" />
    </div>
</div>
    <div class="youtube-player__desc">
        <span class="youtube-player__desc-text--bold"><?php echo $this->getData('description_bold'); ?></span>
        <span class="youtube-player__desc-text"><?php echo $this->getData('description'); ?></span>
    </div>
</div>
<div class="youtube-player-overlay">
    <div class="youtube-player-overlay__close">
        X
    </div>
    <div class="youtube-player-overlay__video">
        <iframe id="youtube-player" class="youtube-player-overlay__player" src="<?php echo $this->getData('iframe_url'); ?>"  width="628" height="619" style="border: solid 4px #37474F" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
    </div>
</div>
