
<div class="youtube-player-overlay">
    <div class="youtube-player-overlay__close">
        X
    </div>
    <div class="youtube-player-overlay__video">
        <iframe id="youtube-player" class="youtube-player-overlay__player" src="<?php echo $this->getData('iframe_url'); ?>" width="628" height="619" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
    </div>
</div>