<section class="header-left">
    <article class="header-left__menu">
        <span class="header-left__menu-bar header-left__menu-bar--top"></span>
        <span class="header-left__menu-bar header-left__menu-bar--bottom"></span>
    </article>
    <article class="header-left__book">
        <a href="<?php echo $this->getUrl('look-book')?>"><i></i></a>
        <div class="header-left__catalog">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-catalogue')->toHtml();?>
        </div>
    </article>
    <article class="header-left__account">
        <a href="/customer/account/login"><i></i></a>
    </article>
</section>