<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
    <a class="header-middle__logo" href="<?php echo $block->getUrl(''); ?>"
        title="<?php /* @escapeNotVerified */ echo $storeName ?>">
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             class="header-middle__desktop-logo"
        />
        <img src='<?php echo $this->getViewFileUrl('img/assets/mobilelogo.png'); ?>'
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             class="header-middle__mobile-logo"
        />
    </a>
