<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
    <a class="header-middle__logo" href="<?php echo $block->getUrl(''); ?>"
        title="<?php /* @escapeNotVerified */ echo $storeName ?>">
    </a>
