<li class="level0">
    <a href="<?php echo $this->getUrl('made-to-measure')?>">Made to Measure</a>
    <ul class="level0">
        <section class="header-middle__row">
            <ol class="header-middle__columns">
                <li class="header-middle__column-item header-middle__column-item--header"><a href="<?php echo $this->getUrl('made-to-measure')?>">Made to Measure</a></li>
            </ol>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menublock-made-to-measure')->toHtml();?>
        </section>
    </ul>
</li>
<li class="level0">
    <a href="<?php echo $this->getUrl('about-us')?>">Brand</a>
    <ul class="level0">
        <section class="header-middle__row">
            <ol class="header-middle__columns">
                <li class="header-middle__column-item header-middle__column-item--header"><a href="<?php echo $this->getUrl('about-us')?>">Get to know us</a></li>
                <li class="header-middle__column-item header-middle__column-item--header"><a href="<?php echo $this->getUrl('blog')?>">Blog</a></li>
                <li class="header-middle__column-item"><a href="<?php echo $this->getUrl('brownlow-skit')?>">Brownlow</a></li>
                <li class="header-middle__column-item"><a href="<?php echo $this->getUrl('msfw-runway')?>">Runway</a></li>
                <li class="header-middle__column-item"><a href="<?php echo $this->getUrl('sustainability')?>">Sustainability</a></li>
            </ol>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menublock-brand')->toHtml();?>
        </section>
    </ul>
</li>
<li class="level0">
    <a href="/instagram/gallery/">Insta</a>
</li>
