<li class="level0">
    <div>
        <a href="#">Stores</a>
    </div>
</li>
<li class="level0">
    <div>
        <a href="#">Editorial
        </a>
    </div>
</li>
<li class="level0">
    <div>
        <a href="#">Brand</a>
        <span class="header-responsive__toggler"></span>
    </div>
    <ul class="level0">
        <section class="header-responsive__row">
            <ol class="header-responsive__columns">
                <li class="header-responsive__column-item header-responsive__column-item--header"><a href="#">Design</a>
                </li>
                <li class="header-responsive__column-item"><a href="#">Our labels explained</a></li>
                <li class="header-responsive__column-item"><a href="#">Mills and productions</a></li>
                <li class="header-responsive__column-item"><a href="#">Sustainability</a></li>
                <li class="header-responsive__column-item"><a href="#">Our campaigns</a></li>
            </ol>
        </section>
    </ul>
</li>
