<li class="level0">
    <a href="#">Brand</a>
    <ul class="level0">
        <section class="header-middle__row">
            <ol class="header-middle__columns">
                <li class="header-middle__column-item header-middle__column-item--header"><a href="#">All Stores</a></li>
                <li class="header-middle__column-item"><a href="#">Queensland</a></li>
                <li class="header-middle__column-item"><a href="#">New South Wales</a></li>
                <li class="header-middle__column-item"><a href="#">Victoria</a></li>
                <li class="header-middle__column-item"><a href="#">South Australia</a></li>
            </ol>
        </section>
    </ul>
</li>
<li class="level0"><a href="#">Editorial</a></li>
<li class="level0">
    <a href="#">Brand</a>
    <ul class="level0">
        <section class="header-middle__row">
            <ol class="header-middle__columns">
                <li class="header-middle__column-item header-middle__column-item--header"><a href="#">Design</a></li>
                <li class="header-middle__column-item"><a href="#">Our labels explained</a></li>
                <li class="header-middle__column-item"><a href="#">Mills and productions</a></li>
                <li class="header-middle__column-item"><a href="#">Sustainability</a></li>
                <li class="header-middle__column-item"><a href="#">Our campaigns</a></li>
            </ol>
        </section>
    </ul>
</li>
