<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php if ($this->showPopup()): ?>
<div id="pslogin-sharepopup" data-bind="scope:'pslogin-sharepopup'" data-mage-init='{"Magento_Ui/js/core/app":<?php echo $block->getJsLayout();?>}' >
	<!-- ko if: showPopup -->
    	<!-- ko template: getTemplate() --><!-- /ko -->
	<!-- /ko -->
</div>
<?php endif; ?>