<?php
/** get tags from store configuration */
$tags = $block->getTags();
/** get view param */
$view = $block->getViewParam();
/** get page param */
$page = $block->getPageParam();
?>
<div class="gallery">
    <?php include($block->getTemplateFile('Magenest_InstagramShop::shared/popup.phtml')) ?>
</div>
<!-- gallery view navigation, includes gallery & tags   -->
<!--<div class="gallery-nav">-->
<!--    <!-- gallery button   -->
<!--    <a href="--><?php //echo $block->getUrl() ?><!--instagram/gallery/">-->
<!--        <div class="gallery-url --><?php //if (empty($view)) echo 'chosen' ?><!--">Gallery</div>-->
<!--    </a>-->
<!--    --><?php
//
//    if (!empty($tags)) {
//        foreach ($tags as $tag) {
//            if (!empty($tag)) {
//                ?>
<!--                <!-- tags button  -->
<!--                <a href="--><?php //echo $block->getUrl() ?><!--instagram/--><?php //echo $tag ?><!--">-->
<!--                    <div class='gallery-url --><?php //if (!empty($view) && $tag == $view) echo 'chosen' ?><!--'>-->
<!--                        --><?php //echo "#" . $tag ?>
<!--                    </div>-->
<!--                </a>-->
<!--                --><?php
//            }
//        }
//    }
//    ?>
<!--</div>-->


<?php

/**
 * @var $block \Magenest\InstagramShop\Block\Gallery\Gallery
 */
$photos = $block->getCollection();

if ($photos->getSize() == 0) {
    echo '<br/><br/><h2 style="clear:both; font-family: Arial, Helvetica, sans-serif; ">There are no photo to display yet, please comeback later</h2>';
} else {
?>
<!-- If found, display photos here    -->
<div class="toolbar" style="margin-top:15px;">
    <?php echo $block->getPagerHtml(); ?>
</div>
<div class="photos-wrapper photo__wrapper">
    <?php
    /** @var \Magenest\InstagramShop\Model\Photo $photo */
    foreach ($photos as $photo) {
        ?>
        <div id="<?= $photo->getPhotoId() ?>">
            <a href="<?php echo $photo->getUrl() ?>">
                <div class="box photo__box">
                    <img src="<?php echo $photo->getSource() ?>" alt="image" class="photo__image"/>
                </div>
            </a>
            <?php
            $count = 0;
            if ($photo->getProductIds() != '') {
                echo '<div id="linked-products" style="display: none;">';
                foreach (explode(', ', $photo->getProductIds()) as $id) {
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    try {
                        /** @var \Magento\Catalog\Model\Product $product */
                        $product = $objectManager->get(Magento\Catalog\Api\ProductRepositoryInterface::class)->getById($id);
                        $productUrl = $product->getUrlModel()->getUrl($product);
                        $imagewidth = 150;
                        $imageheight = 150;
                        $imageHelper = $objectManager->get('\Magento\Catalog\Helper\Image');
                        $image_url = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize($imagewidth, $imageheight)->getUrl();
                        echo '<a class="widget-text-product widget-link-list" data-original-url="' . $productUrl . '" id="product_link_' . $product->getId() . '" target="_blank" data-link-id="' . $product->getId() . '" href="' . $productUrl . '">';
                        echo '<img src="' . $image_url . '" width="150px" height="150px" style=""/>';
                        echo '<span class="widget-link-text-all">';
                        echo '<span class="widget-link-text-number"></span>';
                        echo '<span class="widget-link-text">' . $product->getName() . '</span> </span>';
                        echo '<div class="widget-text-product-cta"></div>';
                        echo '</a>';
                    } catch (\Exception $e) {
                    }
                }
                echo '</div>';
            } else {
                echo '<div id="linked-products" style="display: none;"></div>';
            } ?>
        </div>
        <?php
    }
    ?>
    <div style="clear: both"></div>

    <div class="toolbar-bottom" style="margin-top: 15px;">
        <div class="toolbar">
            <?php echo $block->getPagerHtml(); ?>
        </div>
    </div>
    <?php
    }
    ?>
    <script>
        require(['jquery'], function ($) {
            var photos = <?=json_encode($photos->getData())?>;

            $.fn.chunk = function (size) {
                let array = [];

                for (let i = 0; i < this.length; i += size) {
                    array.push(this.slice(i, i + size));
                }

                return this.pushStack(array, "chunk", size);
            };

            $( '.photo__wrapper > div' ).chunk(5).wrap( '<div class="photo__inner"/>' );

            $( '.photo__inner' ).children('div:first-child').wrap( '<div class="photo__inner--left"/>' );

            $(function () {
                let notFirstChild = $( '.photo__inner > div:not(:first-child)' );

                for ( let i = 0; i < notFirstChild.length; i += 4 ) {
                    notFirstChild.slice(i, i + 4).wrapAll( '<div class="photo__inner--right"/>');
                }
            });



            $('.photos-wrapper div a').on('click', function (e) {
                var self = this;
                e.preventDefault();
                var photo = $.map(photos, function (item) {
                    if ($(self).parent().attr('id') === item.photo_id) {
                        return item;
                    }
                });
                photo = photo[0];
                $('.gallery #widget-instagram-image-url').attr('src', photo.source);
                var html = $(self).parent().children('#linked-products').html();
                console.log(html);
                if (html != '') {
                    $('.gallery .featured-products').show();
                    $('.gallery .widget-text-link-container').html(html);
                } else {
                    $('.gallery .featured-products').hide();
                    $('.gallery .widget-text-link-container').html('');
                }
                $('.gallery #widget-instagram-url').attr('href', photo.url);
                $('.gallery .widget-detail-title').text(photo.caption ? photo.caption : '');
                $('.gallery #created_at_instagram').text(photo.created_at);
                $('.gallery #widget-timeline-detail').data('photo-id', photo.photo_id).removeClass('widget-hidden');

            });
            $('.gallery #widget-detail-close').on('click', function () {
                $('.gallery #widget-timeline-detail').addClass('widget-hidden');
            });

            $('.gallery #widget-prev-post').on('click', function () {
                var photoId = $('.gallery #widget-timeline-detail').data('photo-id');
                $.map(photos, function (item, index) {
                    if (item.photo_id === photoId) {
                        var id = index === 0 ? photos.length : index;
                        return $('.photos-wrapper div#' + photos[id - 1].photo_id + ' a').trigger('click');
                    }
                });
            });
            $('.gallery #widget-next-post').on('click', function () {
                var photoId = $('.gallery #widget-timeline-detail').data('photo-id');
                $.map(photos, function (item, index) {
                    if (item.photo_id === photoId) {
                        var id = index === photos.length - 1 ? -1 : index;
                        return $('.photos-wrapper div#' + photos[id + 1].photo_id + ' a').trigger('click');
                    }
                });
            });

        })
    </script>
</div>



