<div class="page-footer__linkbox">
    <h3>Customer Service</h3>
    <ul>
        <li><a href="{{store url='contact_us'}}">Contact us</a></li>
        <li><a href="{{store url='shipping-returns'}}">Shipping</a></li>
        <li><a href="{{store url='size-chart'}}">Size chart</a></li>
        <li><a href="{{store url='returns-and-exchanges'}}">Returns</a></li>
        <li><a class="faq-click">FAQ</a></li>
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>About Us</h3>
    <ul>
        <li><a href="{{store url='about-us'}}">Our story</a></li>
        <li><a href="{{store url='suit-fit-guide'}}">Suit fit Guide</a></li>
        <li><a href="{{store url='our-mills'}}">Mills &amp; productions</a></li>
        <li><a href="{{store url='sustainability'}}">Sustainability</a></li>
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>My Account</h3>
    <ul>
        <li><a class="myacc-trig" href="{{store url='customer/account/login/'}}">Account sign in</a></li>
        <li><a href="{{store url='checkout/cart/'}}">View cart</a></li>
        {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/footer/wishlistlink.phtml"}}
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>Information</h3>
    <ul>
        <li><a href="{{store url='careers'}}">Careers</a></li>
        <li><a href="{{store url='storelocator'}}">Store Locator</a></li>
        <li><a href="{{store url='terms'}}">Terms &amp; conditions</a></li>
    </ul>
</div>