<div class="page-footer__linkbox">
    <h3>Customer Service</h3>
    <ul>
        <li><a href="{{store url='contact_us'}}">Contact us</a></li>
        <li><a href="{{store url='size-chart'}}">Size charts</a></li>
        <li><a href="{{store url='shipping-returns'}}">Shipping &amp; returns</a></li>
        <li><a class="faq-click">FAQ</a></li>
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>About Us</h3>
    <ul>
        <li><a href="{{store url='about-us'}}">Our story</a></li>
        <li><a href="{{store url='our-design'}}">Design</a></li>
        <li><a href="{{store url='our-labels'}}">Our labels</a></li>
        <li><a href="{{store url='our-mills'}}">Mills &amp; Productions</a></li>
        <li><a href="{{store url='sustainability'}}">Sustainability</a></li>
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>My Account</h3>
    <ul>
        <li><a class="myacc-trig" href="{{store url='customer/account/login/'}}">Sign in</a></li>
        <li><a href="{{store url='checkout/cart/'}}">View cart</a></li>
        {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/footer/wishlistlink.phtml"}}
    </ul>
</div>
<div class="page-footer__linkbox">
    <h3>Information</h3>
    <ul>
        <li><a href="{{store url='careers'}}">Careers</a></li>
        <li><a href="{{store url='storelocator'}}">Store Locator</a></li>
        <li><a href="{{store url='terms'}}">Terms and Conditions</a></li>
    </ul>
</div>