<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/clothing/shirts-1.html"> <img src="{{media url="wysiwyg/menublock-images/Shirts-Tile.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/clothing/sports-jackets-1.html"> <img src="{{media url="wysiwyg/menublock-images/SportsJackets.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/clothing/mens-chinos.html"> <img src="{{media url="wysiwyg/menublock-images/Chinos-Tile.jpg"}}"
            alt="" /> </a></figure>
</section>