<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/mens-suits-1.html"> <img src="{{media url="wysiwyg/menublock-images/AnyTwoFor795.jpg"}}" alt=""
            /> </a></figure>
    <figure><a href="/mens-suits-1.html"> <img src="{{media url="wysiwyg/menublock-images/AW18-New-Ccollection.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/mens-suits-1/vests.html"> <img src="{{media url="wysiwyg/menublock-images/Vests.jpg"}}" alt=""
            /> </a></figure>
</section>