<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/clothing/shirts-1.html"> <img src="{{media url="wysiwyg/menublock-images/Shirts_4.jpg"}}" alt="" /> </a></figure>
    <figure><a href="/clothing/sports-jackets-1.html"> <img src="{{media url="wysiwyg/menublock-images/sports_jacket_1.jpg"}}" alt="" /> </a></figure>
    <figure><a href="/clothing/coats.html"> <img src="{{media url="wysiwyg//menublock-images/coats.jpg"}}" alt="" /> </a></figure>
</section>