<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/explore-new-arrivals.html"> <img src="{{media url="wysiwyg/menublock-images/AW18-New-Ccollection.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/mens-suits-1/formal-wear.html"> <img src="{{media url="wysiwyg/menublock-images/Formal-Wear-Tile.jpg"}}" alt=""
            /> </a></figure>
    <figure><a href="/mens-suits-1/seasonal-highlights.html"> <img src="{{media url="wysiwyg/menublock-images/WINTER-HIGHLIGHTS-Tile.jpg"}}" alt=""
            /> </a></figure>
</section>