<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/made-to-measure"> <img src="{{media url="wysiwyg/menublock-images/MadeToMeasure.jpg"}}" alt="" />
        </a></figure>
    <figure><a href="/made-to-measure"> <img src="{{media url="wysiwyg/menublock-images/PersonalTailoring.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/made-to-measure"> <img src="{{media url="wysiwyg/menublock-images/BookAnAppointment.jpg"}}"
            alt="" /> </a></figure>
</section>