<div class="std">
    <h3>Online Shipping</h3>

    <p>We will always aim to deliver online orders within the allotted time frame from dispatch to shipping, however we
        cannot promise an exact date of delivery at the time of purchase.</p>

    <p>We shall always aim to inform our customers if we expect that we are unable to meet our estimated delivery date,
        but, to the extent permitted by law, we shall not be liable to you for any losses, liabilities, costs, damages,
        charges or expenses arising out of a late delivery.&nbsp;</p>

    <p>Before you confirm your order, please double check the shipping details as we are unable to make changes once
        your order has been processed online.&nbsp;</p>

    <h3>Confirmation</h3>
    <p>Once your order is processed you will receive a confirmation email. This will be received by COB on the date of
        purchase. If your order is placed outside of standard operating hours (weekends, public holiday or after
        standard operating hours), the confirmation email will be delivered by COB the following business day.</p>

    <p>The confirmation email will only confirm the that your order has been processed and will not include an estimated
        time of delivery or a tracking number. A tracking number will only be received at the time of dispatch.</p>

    <h3>Dispatch</h3>
    <p>Dispatch refers to when your garments leave our Distribution Centre. On the day of dispatch, you will receive an
        email confirming that your order has left our Distributions Centre. This email will contain your Australia Post
        Tracking Number, which can be used on the Australia Post Website.&nbsp;</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Orders can take between 3 – 5
        business days to be dispatched.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Orders are not dispatched over
        the weekend or Victorian public holidays.</p>
    <p>During heavy trading periods, there are times where we may need to source your garment order from stores across
        our network, which will delay dispatch. In this case our Customer Care team will contact you via email to
        inform you of the expected delay.
    </p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>You will receive
        an email at 5pm EST on the day your order has been dispatched.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>All orders are
        dispatched from our Victorian Head office, Abbotsford, Melbourne.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Please be aware,
        Dispatch period does not include standard shipping times.</p>
</div>

<div class="std">
    <h3>Shipping Methods</h3>

    <p><strong>Standard Shipping - $10</strong></p>
    <p><strong>Free for orders over $100</strong></p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Melbourne Metro –
        expect delivery 1-3 Business Days from Dispatch.&nbsp;</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>All other capital
        cities – delivery is between 3-5 Business Days from Dispatch.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Regional
        Australia – allow a little longer, 5-7 Business Days from Dispatch.</p>

    <h3>Express shipping - $15</h3>
    <p>•<span> <span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span></span>Metroplitan
        Cities (Australia) - Guaranteed 1-2 Business Days from Dispatch.</p>
    <p>•<span> <span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span></span>Regional
        Australia – &nbsp;3-4 Business Days from Dispatch.</p>
</div>

<div class="std">
    <h3>International Shipping</h3>

    <p><strong>International shipping - $30</strong></p>

    <p>We currently ship internationally to New Zealand only.</p>

    <p>A customer care representative will contact you via phone or email to process this additional charge.</p>

    <p><strong>PLEASE NOTE: THE ONLINE CHECKOUT WILL PROCESS VIA AUSTRALIA POST ECONOMY AIR FREE SHIPPING. THIS WILL BE
            CHARGED AT $30.00 AUD.</strong></p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>All New Zealand – expected
        delivery 7-10 business days from dispatch.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Orders in AUD which are
        equivalent to NZ$200 shipped to New Zealand may incur GST, customs charges and duties charged by the NZ Customs
        Service once the parcel reaches its destination port and must be paid by the recipient directly to the NZ Cus
        toms Service or its authorised service provider. Peter Jackson Pty Ltd. is not responsible for and will not
        reimburse any of these charge and duties.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Customs charges and duties
        are the responsibility of the Customer and will not be refunded by Peter Jackson Pty Ltd. There are limited
        times when only the duty and GST can be refunded to you by the NZ Customs Service.</p>

    <p>Find out more here: <a href="http://www.customs.govt.nz/features/internetshopping/Pages/Refunds-when-you-return-an-item.aspx">http://www.customs.govt.nz/features/internetshopping/Pages/Refunds-when-you-return-an-item.aspx</a></p>
</div>

<div class="std">
    <h3>Tracking Parcels</h3>

    <p>You can track your Standard, Express or International parcels via the Australia Post website. As a registered
        customer you will receive a tracking number in your dispatch confirmation email.</p>

    <p>If your parcel hasn't arrived in the estimated time period, please refer to the Australia Post website here to
        see if delivery of your parcel has been attempted. Peter Jackson Australia Pty. cannot accept responsibility
        for delays, damages or loss of orders following handover to Australia Post.</p>
</div>

<div class="std">
    <h3>Stock Availability</h3>

    <p>Our stock levels change frequently and there may be some garments only available online for a limited time.
        If the size you are after is not available online, simply contact our Customer Service team (03 9415 6281) and
        they will do their best to track the right size down for you.</p>

    <p>There may also be times where a garment purchased via our website is not available in our online warehouse when
        we come to dispatch. In this case we will do our best to source the garment from one of our stores and email
        you about this within one working day of your order.</p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Drop the parcel at your
        nearest post office. We ask that you cover the cost of the return.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Once we have received your
        return parcel we will be in touch with an update on the return process.</p>
</div>