<section class="size-chart" id="size-chart">
    <section class="size-chart__overlay">
        <div class="size-chart__close"><span>Close</span>
            <figure class="size-chart__close-icon"></figure>
        </div>
        <section class="size-chart__charts">
            <div class="suit-label-chart label-chart">
                <section class="size-chart__tabs" id="element"
                         data-mage-init='{"accordion":{"collapsible": true, "active": true, "multipleCollapsible": false, "disabled": false}}'>
                    <div data-role="collapsible">
                        <div data-role="trigger">
                            <a href="#chart-suits" class="size-chart__tab size-chart__tab--active">Suits</a>


                            <div data-role="content">
                                <a href="#chart-shirts" class="size-chart__tab">Shirts</a>
                                <a href="#chart-trousers" class="size-chart__tab">Trousers & Chinos</a>
                                <a href="#chart-accessories" class="size-chart__tab">Accessories</a>
                                <a href="#chart-shoes" class="size-chart__tab">Shoes</a>
                            </div>
                        </div>
                    </div>
                </section>
                <article class="size-chart__section size-chart__section--active" data-href="#chart-suits">
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                88
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                92
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                96
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                100
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                104
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                108
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                112
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                116
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                120
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                124
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                128
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                132
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span></span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>34</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>36</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>38</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>40</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>42</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>44</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>46</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>48</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>50</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>52</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>54</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>56</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Chest</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>47.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>49.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>51.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>53.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>55.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>57.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>59.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>61.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>63.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.5</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Waist</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>42.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>44.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>46.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>53.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>55.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>57.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>59.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>61.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>63.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.5</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Sleeve</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Short</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>60.3</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>61.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>61.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>62.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>63.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>64.3</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>66.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.2</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.4</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.7</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Regular</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>62.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>63.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>63.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>64.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>66.3</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>67.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>68.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.4</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.8</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Long</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>64.3</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>65.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>66.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>66.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>68.3</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>70.7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>71.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>71.4</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>71.7</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Back Seam</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Short</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>68.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>69.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>70.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>71.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>72.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>73.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>74.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>75.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>76.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>77.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>77.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>78.1</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Regular</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>70.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>71.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>72.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>73.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>74.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>75.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>76.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>77.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>78.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>79.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>79.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80.1</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Long</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>73.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>74.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>75.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>76.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>77.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>78.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>79.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>81.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>83.1</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="size-chart__table size-chart__information">
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Chest</span>
                            </div>
                            <div class="size-chart__information--font-size">
                                <span>Measure at fullest part of the body</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Waist</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>Measure around body at hip height</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Sleeve Length</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>With arm bent at 90&#176;, measure from the middle of the
                                    neck across the shoulder and down to the wrist.</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Back Seam</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>Measure from the start of your neck down to your natural waistline.</span>
                            </div>
                        </div>
                    </div>
                </article>
                <article class="size-chart__section" data-href="#chart-shirts">
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                S
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                S
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                M
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                M
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                L
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                L
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                XL
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                XL
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                2XL
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                2XL
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                3XL
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>Neck</span><span class="size"> (CM)</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>37</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>38</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>39</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>40</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>41</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>42</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>43</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>44</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>46</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>48</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>50</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>Chest</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>100</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>104</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>108</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>110</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>114</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>118</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>122</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>126</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>130</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>134</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>142</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>Sleeve</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>61.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>61.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>63.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>63.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>65</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>65</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>66.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>66.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>68</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>68</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>69.5</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>Shoulder</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>45</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>46</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>47</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>48</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>49</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>50</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>51</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>52</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>53</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>54</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>56</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="size-chart__table size-chart__information">
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Neck</span>
                            </div>
                            <div class="size-chart__information--font-size">
                                <span>Measure around base of neck</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Chest</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>Measure at fullest part of the body</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Shoulder</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>Measure across shoulder at back</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Sleeve length</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>With arm bent at 90&#176;, measure from the middle of the
                                    neck across the shoulder and down to the wrist.</span>
                            </div>
                        </div>
                    </div>
                </article>
                <article class="size-chart__section" data-href="#chart-trousers">
                    <h2 class="size-chart__header">Dexter Trousers & Chinos - DROP 14</h2>
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size<span class="space">(CM)</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                76
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                80
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                84
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                88
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                92
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                96
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                100
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                104
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                108
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                112
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                116
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span class="double-space">(INCH)</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                28
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                30
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                32
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                34
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                36
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                38
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                40
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                42
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                44
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                46
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                48
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Waist</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>79</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>83</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>87</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>91</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>95</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>99</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>103</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>107</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>111</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>115</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>119</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>INLEG</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Short</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Regular</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Long</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>FOOT DIA.</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>20</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <h2 class="size-chart__header">Tarintino Trousers - DROP 12</h2>
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size<span class="space">(CM)</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                76
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                80
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                84
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                88
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                92
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                96
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                100
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                104
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                108
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                112
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                116
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span class="double-space">(INCH)</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                28
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                30
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                32
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                34
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                36
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                38
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                40
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                42
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                44
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                46
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                48
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>Waist</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>79</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>83</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>87</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>91</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>95</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>99</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>103</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>107</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>111</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>115</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>119</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>INLEG</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Short</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>80</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Regular</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>82</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>Long</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>85</span>
                            </div>
                        </div>
                        <div class="size-chart__row size-chart__row--blank">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>FOOT DIA.</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>18</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="size-chart__table size-chart__information">
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Waist</span>
                            </div>
                            <div class="size-chart__information--font-size">
                                <span>Measure around the body at hip height</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>Inleg</span>
                            </div>
                            <div  class="size-chart__information--font-size">
                                <span>Measure from the lowest part of your crotch area to the hem.</span>
                            </div>
                        </div>
                    </div>
                </article>
                <article class="size-chart__section" data-href="#chart-accessories">
                    <h2 class="size-chart__header">Belts</h2>
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size<span class="space">(CM/INCH)</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                77/30
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                82/32
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                87/34
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                92/36
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                97/38
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                102/40
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                107/42
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                112/44
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold" style="flex-grow: 2;">
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                S
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                M
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                M
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                L
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                L
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                XL
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                2XL
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                3XL
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                <span>BELT LENGTH</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>(CM)</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>80</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>86</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>90</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>96</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>100</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>106</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>110</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>116</span>
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--space"
                                 style="flex-grow: 2;">
                                <span>(INCH)</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center">
                                <span>32</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>34</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>36</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>38</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>40</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>42</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>44</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                <span>46</span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <h2 class="size-chart__header">Socks</h2>
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                Size
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                                6-13
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                            <div class="size-chart__box size-chart__box--center">
                            </div>
                        </div>
                    </div>
                    <hr>
                </article>
                <article class="size-chart__section" data-href="#chart-shoes">
                    <hr>
                    <div class="size-chart__table">
                        <div class="size-chart__row size-chart__table--size">
                            <div class="size-chart__box size-chart__box--bold"
                                 style="flex-grow: 2;">
                                UK
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                5
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                6
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                7
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                8
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                9
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                10
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                11
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                                12
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding-center">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>US</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>6</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>7</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>8</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>10</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>11</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>12</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>13</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>EU</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>39</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>40</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>41</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>42</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>43</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>44</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>45</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>46</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                        </div>
                        <div class="size-chart__row">
                            <div class="size-chart__box size-chart__box--bold size-chart__box--bold-center"
                                 style="flex-grow: 2;">
                                <span>LENGTH</span>
                            </div>
                            <div class="size-chart__box size-chart__table--size size-chart__box--center size-chart__box--padding">
                                <span>24.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>25.4</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>26.2</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>27.1</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>27.9</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>28.8</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>29.6</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                                <span>30.5</span>
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                            <div class="size-chart__box size-chart__box--center size-chart__box--padding">
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="size-chart__table size-chart__information">
                        <div class="size-chart__row">
                            <div class="size-chart__information--box size-chart__information--bold size-chart__information--padding"
                                 style="flex-grow: 0;">
                                <span>HOW TO FIND YOUR
                                    <br>FOOT SIZE</span>
                            </div>
                            <div class="size-chart__information--font-size">
                                <span>Measure your foot from one tip to the other. If after measuring your foot and
                                    consulting the table you find that you are between two sizes, you must opt
                                    for the larger size.</span>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </section>
    </section>


    <section class="size-chart-mobile">
        <div class="size-chart-mobile__header">
            <div class="size-chart-mobile__header--left">Size<span>(CM/INCH)</span></div>
            <div class="size-chart-mobile__header--right">Measurements</div>
        </div>
        <div class="size-chart-mobile__row">
            <div class="size-chart-mobile__row--left">88/34</div>
            <div class="size-chart-mobile__row--right">
                <div>Chest 47.5</div>
                <br>
                <div>Waist 42.5</div>
                <br>
                <div>Sleeve 62.3</div>
                <br>
                <div>Back seam 70.5</div>
            </div>
        </div>
        <hr>
        <div class="size-chart-mobile__row">
            <div class="size-chart-mobile__row--left">92/36</div>
            <div class="size-chart-mobile__row--right">
                <div>Chest 49.5</div>
                <br>
                <div>Waist 44.5</div>
                <br>
                <div>Sleeve 63.1</div>
                <br>
                <div>Back seam 71.5</div>
            </div>
        </div>
        <hr>
        <div class="size-chart-mobile__row">
            <div class="size-chart-mobile__row--left">96/38</div>
            <div class="size-chart-mobile__row--right">
                <div>Chest 51.5</div>
                <br>
                <div>Waist 46.5</div>
                <br>
                <div>Sleeve 63.9</div>
                <br>
                <div>Back seam 72.5</div>
            </div>
        </div>
        <hr>
    </section>
</section>

<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#element").collapsible();
    });
</script>