<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <figure
       class="action towishlist"
       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
    </figure>
<?php endif; ?>

