<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>

    <?php if ($block->getWishlistHelper()->isAllow()): ?>
        <a
                class="action towishlist"
                title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
                data-action="add-to-wishlist"
        >
            <figure class="catalog-item__star"></figure>
        </a>
    <?php endif; ?>


