<div class="checkout-footer">
        <div class="checkout-footer__wrapper">
            <div class="comodo-trust-logo">
                <span>SHOP WITH CONFIDENCE</span>
                <span>Secure checkout 256 BIT SSL Encryption</span>
            </div>
            <div class="checkout-footer__payment-graphics">
                <figure class="checkout-footer__credit-cards"></figure>
            </div>
            <div><a class="shipping-returns-click">FREE SHIPPING AUSTRALIA WIDE*</a></div>
        </div>
</div>
