<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>

<?php foreach ($methods as $method): ?>
    <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
    <?php /* @escapeNotVerified */ echo $methodHtml; ?></li>
    <?php endif; ?>
<?php endforeach; ?>

<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "PandaGroup_Checkout/js/cart-floater": {}
        }
    }
</script>