<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div class="header-right__minicart header-right__minicart--desktop" data-block="minicart">
    <a class="action showcart header-right__url-block" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'"><i class="header-right__minicart-icon filtered-on-header"></i>
        <span class="header-right__counter filtered-on-header"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "0",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "show":{"effect":"slide", "direction": "up", "duration":900},
                "hide":{"effect":"slide", "direction": "up", "duration":900},
                "parentClass":"active",
                "buttons":[]}}'>
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>

            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>

    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>
<div class="header-right__minicart header-right__minicart--mobile" data-block="minicart">
    <a class="header-right__url-block" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <i class="header-right__minicart-icon filtered-on-header"></i>
        <span class="header-right__counter filtered-on-header"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
        </span>
    </a>
</div>
