<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $categoryCode = 'default';
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    if ($category != null) {
        $categoryCode = strtolower($category->getName());
    }

    if ($block->getMode() == 'grid') {
        // grid == 3 col
        $viewMode = 'grid';
        if($categoryCode === 'suits') {
            $image = 'category_page_3col_suits';
        } else {
            $image = 'category_page_3col';
        }
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        // list == 2 col
        $viewMode = 'list';
        if($categoryCode === 'suits') {
            $image = 'category_page_2col_suits';
        } else {
            $image = 'category_page_2col';
        }
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items catalog-grid">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ?
                    '<li class="item product product-item catalog-grid__item catalog-item catalog-item--' .  $viewMode . '">'
                    : '</li><li class="item product product-item catalog-grid__item catalog-item catalog-item--' .  $viewMode . '">' ?>
                <div class="product-item-info catalog-item__info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo catalog-item__img" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                        <?php $productImageAttr = $_product->getCustomAttribute('hover_image'); ?>
                        <?php if ($productImageAttr):
                            $productHoverImage = $this->helper('Magento\Catalog\Helper\Image')
                                ->init($_product, 'hover_image')
                                ->keepAspectRatio(true)
                                ->resize($productImage->getWidth(), $productImage->getHeight())
                                ->setImageFile($productImageAttr->getValue());?>
                            <img class="catalog-item__img--second" width="<?php echo $productImage->getWidth()?>" height="<?php echo $productImage->getHeight() ?>" src="<?php echo $productHoverImage->getUrl(); ?>" />
                        <?php endif; ?>
                    </a>
                    <div class="product details product-item-details catalog-item__content">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h3 class="product name product-item-name catalog-item__product-name">
                            <a class="product-item-link catalog-item__title"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h3>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php $promo_block = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-' . $categoryCode)->toHtml(); ?>
                        <?php if ($promo_block): ?>
                            <div class="catalog-item__promo">
                                <?php echo $promo_block; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

