<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<div class="items-table__row items-table__row--item">
    <div class="items-table__column items-table__column--remove items-table__column--centred">
        <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
    </div>

    <div class="items-table__column items-table__column--item" data-th="<?php echo $block->escapeHtml(__('Item')); ?>" >
        <?php if ($block->hasProductUrl()):?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
               title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo items-table__product-image">
        <?php else:?>
            <span class="product-item-photo items-table__product-image">
        <?php endif;?>
        <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
        <?php if ($block->hasProductUrl()):?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details items-table__product-details">
            <span class="product-item-name items-table__product-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </span>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options items-table__product-params">
                    <dt>Product Code: </dt><dd><?php /* @escapeNotVerified */ echo $_item->getSku() ?></dd>
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_cssClass = "class='items-table__product-params-{$_option['label']}'"?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <br><dt <?php echo $_cssClass ?>><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd <?php echo $_cssClass ?>>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                    <br><dt class="items-table__product-params-delivery">Est. delivery: </dt><dd class="items-table__product-params-delivery">placeholder</dd>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </div>

    <div class="items-table__column items-table__column--qty items-table__column--centred" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="select__wrapper select__wrapper--cart-qty">
            <figure class="select__arrow"></figure>
            <select class="select__select"
                    id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                    name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                    data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                    title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                    data-validate="{required:true,'validate-greater-than-zero':true}"
                    data-role="cart-item-qty"
                    >
                    <?php $value = $block->getQty();
                    for ($i = 1; $i <= 10; $i++) {
                        if ($i == $value) {
                            echo "<option value='{$i}' selected>{$i}</option>";
                        } else {
                            echo "<option value='{$i}'>{$i}</option>";
                        }
                    }
                    ?>
            </select>
        </div>
    </div>

    <div class="items-table__column items-table__column--size items-table__column--centred">
        <div class="select__wrapper select__wrapper--cart-size">
            <figure class="select__arrow"></figure>
            <select class="select__select">
            <?php for ($i = 1; $i <= 10; $i++) {
                        echo "<option value='{$i}' selected>{$i}</option>";
                }
            ?>
        </select>
            </div>
    </div>

    <div class="items-table__column items-table__column--price items-table__column--centred-right" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php $normal_price = $_item->getProduct()->getPrice();
        $special_price = $_item->getProduct()->getSpecialPrice();?>
        <?php if ($special_price):?>
            <span class="items-table__price items-table__price--special"><?php echo $priceHelper->currency($special_price, true, false);?></span>
            <span class="items-table__price items-table__price--strikethrough"><?php echo $priceHelper->currency($normal_price, true, false); ?></span>
        <?php else: ?>
            <span class="items-table__price"><?php echo $priceHelper->currency($normal_price, true, false); ?></span>
        <?php endif;?>
    </div>
</div>

