<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $block \Amasty\GiftCard\Block\Customer\CardForm */ ?>
<div class="amgiftcard">
    <form class="form" id="amgiftcard-form" action="<?php echo $block->getUrl('amgiftcard/account/addCard') ?>" method="post" enctype="multipart/form-data">
        <?php echo $block->getBlockHtml('formkey')?>
        <fieldset class="fieldset gift-card__box">
            <legend class="legend gift-card__header"><span data-title="change-email-password"><?php echo __('Gift Cards') ?></span></legend><br>
            <div class="field required" data-container="change-email">
                <div class="control">
                    <input type="text" class="required-entry input-text gift-card__code" id="am_giftcard_code" name="am_giftcard_code" value="" placeholder="Enter gift card code"/>
                </div>
            </div>
        </fieldset>

        <div class="buttons-set form-buttons btn-only">
            <button type="submit" class="action save primary gift-card__button" title="<?php echo __('Check Balance') ?>"><span><?php echo __('Check Balance') ?></span></button>
        </div>
    </form>
</div>