<div>
    <p>After install, the Lazy Load Extension will run on Category, Product View and Related Products or Up Sell. If you like to make it run on other pages here are a few simple steps:</p>
    <p>1. Add the html class "lazy" to the img element</p>
    <p>2. Add the html data-original attribute with the path to the image</p>
    <p>3. Add a image in "src" attribute which will be displayed before the image loads (usually it's a gif animated image)</p>
    <p>Here is the full example (&lt;img class=“lazy” src=“path/to/loader-image/loading.gif” data-original=“path/to/image/image.jpg” alt=“” /&gt;)</p>
</div>