<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer account-login__register">
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <div class="actions-toolbar">
            <div class="primary account-login__row account-login__row--register">
                <p class="account-login__noaccount"><?php /* @escapeNotVerified */ echo __('No account') ?>?</p>
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action create primary account-login__link account-login__noaccount--link"><span><?php /* @escapeNotVerified */ echo __('Sign up now') ?>.</span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
