<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /** @var $block \Amasty\GiftCard\Block\Product\View\Type\GiftCard */ ?>
<?php $_currencyShortName = $block->getCurrencyShortName(); ?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable() && $block->isConfigured($_product)) : ?>
    <div class="product-info-main__field fieldset">
        <?php if ($block->isMultiAmount() || $_product->getAmGiftcardPrices()) : ?>
            <div class="product-info-main__field field required">
                <label class="product-info-main__label label" for="amgiftcard_amount">
                    <span><?= __('Card Value in %1', $_currencyShortName); ?></span>
                </label>
                <?php if ($block->isPredefinedAmount()) : ?>
                    <div class="control select__wrapper required-entry">
                        <figure class="select__wide-arrow"></figure>
                        <select id="am_giftcard_amount" name="am_giftcard_amount" class="select__pdp-select required-entry">
                            <option value=""><?= __('Choose an Amount...'); ?></option>
                            <?php foreach ($block->getListAmounts() as $_amount) : ?>
                                <option data-value="<?= $block->convertPrice($_amount); ?>"
                                        value="<?= $block->convertPrice($_amount) ; ?>"
                                    <?php if ($block->getDefaultValue('am_giftcard_amount') == $_amount) :
                                        echo " selected";
                                    endif; ?>><?= $block->getFormatPrice($_amount); ?></option>
                            <?php endforeach; ?>
                            <?php if ($_product->getAmAllowOpenAmount()) : ?>
                                <option value="custom"><?= __('Custom Amount'); ?></option>
                            <?php endif; ?>
                        </select>

                        <?php if ($_product->getAmAllowOpenAmount()) : ?>
                            <div class="product-info-main__field field" id="amgiftcard_amount_custom_block"
                                 style="display: <?php if ($block->isPredefinedAmount()): ?>none<?php endif; ?>">
                                <?php $_min = $_max = 0;
                                if ($_product->getAmOpenAmountMin() || $_product->getAmOpenAmountMax()) : ?>
                                    <?php $_min = $_product->getAmOpenAmountMin(); ?>
                                    <?php $_max = $_product->getAmOpenAmountMax(); ?>
                                    <input id="am_giftcard_amount_custom" name="am_giftcard_amount_custom"
                                           class="product-info-main__input validate-number-range number-range-<?= $block->round($block->convertPrice($_min)) . '-' . $block->round($block->convertPrice($_max)); ?>
                                           required-entry input-text amgiftcard-min-amount amgiftcard-max-amount"
                                           value="<?= $block->getDefaultValue('am_giftcard_amount_custom'); ?>"
                                           type="text">

                                    <div>
                                        <?php if ($_product->getAmOpenAmountMin()) : ?>
                                            <span><?= __('Minimum: %1', $block->getFormatPrice($_min));?></span>
                                        <?php endif; ?>

                                        <?php if ($_product->getAmOpenAmountMax()) : ?>
                                            <span><?= __('Maximum: %1', $block->getFormatPrice($_max));?></span>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if ($_product->getAmGiftcardType() == \Amasty\GiftCard\Model\GiftCard::TYPE_COMBINED) : ?>
            <div class="product-info-main__field field required">
                <label for="am_giftcard_type" class="product-info-main__label label">
                    <span><?= __('Choose card type'); ?></span>
                </label>
                <div class="input-box select__wrapper required-entry">
                    <figure class="select__wide-arrow"></figure>
                    <select id="am_giftcard_type" name="am_giftcard_type" class="select__pdp-select required-entry">
                        <option value=""><?= __('-- Please Select --'); ?></option>
                        <?php foreach ($block->getListCardTypes() as $_cardType) : ?>
                            <option
                                    value="<?= $_cardType['value']; ?>"
                                <?php if ($block->getDefaultValue('am_giftcard_type') == $_cardType['value']) :
                                    echo " selected";
                                endif; ?>><?= $_cardType['label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note am-giftcard-delivery-info" style="display: none">
                        <?= __('Please be aware that printed gift card will be sent to the shipping address you specify during checkout.'); ?>
                    </p>
                </div>
            </div>

        <?php endif; ?>

        <?php if ( $_images = $block->getImages() ): ?>
            <input type="text" id="am_giftcard_image" name="am_giftcard_image" style="display:none;"
                   value="1>"/>
        <?php endif; ?>

        <?php if ($block->isOptionEnable('am_giftcard_sender_name')) : ?>
            <div class="product-info-main__field field required">
                <label for="am_giftcard_sender_name" class="label">
                    <span><?= __('Sender Name'); ?></span>
                </label>
                <div class="input-box">
                    <input type="text" id="am_giftcard_sender_name" name="am_giftcard_sender_name"
                           class="product-info-main__input required-entry input-text" value="<?= $block->getCustomerName(); ?>"/>
                </div>
            </div>
        <?php endif; ?>

        <div class="product-info-main__field field required">
            <label for="am_giftcard_sender_email" class="label">
                <span><?= __('Sender Email'); ?></span>
            </label>
            <div class="input-box">
                <input type="text" id="am_giftcard_sender_email" name="am_giftcard_sender_email"
                       class="product-info-main__input validate-email required-entry input-text"
                       value="<?= $block->getCustomerEmail(); ?>"/>
            </div>
        </div>

        <?php if ($_product->getAmGiftcardType() != \Amasty\GiftCard\Model\GiftCard::TYPE_PRINTED) : ?>
            <?php if ($block->isOptionEnable('am_giftcard_recipient_name')) : ?>
                <div class="product-info-main__field field required am_giftcard_recipient_data">
                    <label for="am_giftcard_recipient_name" class="label">
                        <span><?= __('Recipient Name'); ?></span>
                    </label>
                    <div class="input-box">
                        <input type="text" id="am_giftcard_recipient_name" name="am_giftcard_recipient_name"
                               class="product-info-main__input required-entry input-text"
                               value="<?= $block->getDefaultValue('am_giftcard_recipient_name'); ?>"/>
                    </div>
                </div>
            <?php endif; ?>
            <div class="product-info-main__field field required am_giftcard_recipient_data">
                <label for="am_giftcard_recipient_email" class="product-info-main__label label">
                    <span><?= __('Recipient Email'); ?></span>
                </label>
                <div class="input-box">
                    <input type="text" id="am_giftcard_recipient_email" name="am_giftcard_recipient_email"
                           class="product-info-main__input validate-email required-entry input-text"
                           value="<?= $this->getDefaultValue('am_giftcard_recipient_email'); ?>"/>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable('am_giftcard_date_delivery')) : ?>
            <div class="field required">
                <label for="am_giftcard_date_delivery" class="label">
                    <span><?= __('Date of Certificate Delivery'); ?></span>
                </label>
                <div class="input-box">
                    <input name="am_giftcard_date_delivery" id="am_giftcard_date_delivery"
                           value="<?= $block->getDefaultValue('am_giftcard_date_delivery'); ?>"
                           class="required-entry datetime-picker input-text validate-date"
                           type="text">
                    <p class="note am-giftcard-delivery-info" style="display:none;">
                        <?= __('Please be aware that delivery date of printed certificates may be different due to post.'); ?>
                    </p>
                </div>
            </div>
            <div class="field required">
                <label for="am_giftcard_date_delivery_timezone" class="label">
                    <span><?= __('Select timezone'); ?></span>
                </label>
                <div class="input-box">
                    <select class="required-entry" name="am_giftcard_date_delivery_timezone"
                            id="am_giftcard_date_delivery_timezone">
                        <option value=""></option>
                        <?php foreach ($block->getListTimezones() as $_timezone) : ?>
                            <option
                                    value="<?= $_timezone['value']; ?>"<?php if ($block->getDefaultValue('am_giftcard_date_delivery_timezone') == $_timezone['value']) {
                                echo " selected";
                            } ?>><?= $_timezone['label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable(\Amasty\GiftCard\Model\Options::GIFT_MESSAGE)) : ?>
            <div class="product-info-main__field field">
                <label for="am_giftcard_message" class="product-info-main__label label">
                    <span><?= __('Message'); ?></span>
                </label>
                <div class="input-box">
					<textarea name="am_giftcard_message" id="am_giftcard_message" class="product-info-main__textarea input-text" cols="5"
                              rows="3"><?= $block->getDefaultValue('am_giftcard_message'); ?></textarea>
                </div>
            </div>
        <?php endif; ?>

        <script>
            require([
                'jquery',
                'Amasty_GiftCard/js/main',
                "mage/calendar"
            ], function ($) {
                $('#am_giftcard_sender_email').amGiftcard({
                    productId: "<?= $_product->getId(); ?>",
                    feeType: "<?= $_product->getAmGiftcardFeeType(); ?>",
                    feeValue: "<?= $_product->getAmGiftcardFeeValue(); ?>"
                });
                if ($("#am_giftcard_date_delivery")) {
                    $("#am_giftcard_date_delivery").calendar({
                        showTime: false,
                        minDate: new Date(),
                    });
                }
            });

        </script>
    </div>
<?php endif; ?>
