<div class="page-footer__upper">
    <div class="page-footer__upper-upper">
        <div class="page-footer__signup-wrapper">
            <div class="page-footer__signup">
                <h3>Sign up to receive style news</h3>
                <!-- Begin Salesforce Signup Form -->
                <div>
                    <form action="https://pub.s7.exacttarget.com/ce14bqbgxxy" id="subscribe-form-footer" name="subscribeForm" method="post">
                        <div class="newsletter">
                            <div class="newsletter__input-wrap"><input type="text" required class="newsletter__input" name="name" placeholder="First name"></div>
                            <div class="newsletter__input-wrap"><input type="email" required class="newsletter__input" name="email" placeholder="Email Address"></div>
                            <input type="hidden" name="Source" value="Footer" />
                            <div class="newsletter__button-wrap"><input type="submit" value="Submit" class="button newsletter__submit"></div>
                            <div class="newsletter__messages"></div>
                        </div>
                    </form>
                </div>
                <!-- End Salesforce Signup Form -->
                <div class="popup-success">
                    <div class="popup-success__content">
                        <div class="popup-success__close">x</div>
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup-success')->toHtml();?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-footer__upper-lower">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links')->toHtml();?>
        <div class="page-footer__linkbox page-footer__social-icons">
            <h3>Socialise With Us</h3>
            <ul class="page-footer__social-icons-ul">
                <li><a href="https://www.facebook.com/peterjacksonmenswear" target="_blank" class="page-footer__icon page-footer__icon--fb"></a></li>
                <li><a href="https://instagram.com/peterjacksonau/" target="_blank" class="page-footer__icon page-footer__icon--instagram"></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="page-footer__lower">
    <div class="page-footer__lower-wrapper">
        <div class="page-footer__lower-linkbox page-footer__lower-linkbox--comodo" data-mage-init='{"js/comodo":{}}' >
            <p>Secure checkout 256 BIT SSL Encryption</p>
        </div>
        <div class="page-footer__lower-linkbox page-footer__lower-linkbox--cards">
            <figure class="page-footer__cards page-footer__cards--visa"></figure>
            <figure class="page-footer__cards page-footer__cards--mastercard"></figure>
        </div>
        <div class="page-footer__lower-linkbox page-footer__lower-linkbox--copyright">
            <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
        </div>
        <div class="page-footer__lower--social-icons">
            <h3>Socialise With Us</h3>
            <ul class="page-footer__social-icons-ul">
                <li><a href="https://www.facebook.com/peterjacksonmenswear" target="_blank" class="page-footer__icon page-footer__icon--fb"></a></li>
                <li><a href="https://instagram.com/peterjacksonau/" target="_blank" class="page-footer__icon page-footer__icon--instagram"></a></li>
            </ul>
        </div>
    </div>
</div>
