<div class="page-footer__upper">
    <div class="page-footer__upper-wrapper">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links')->toHtml();?>
        <div class="page-footer__linkbox">
            <h3>Peter Jackson VIP Sign up</h3>
            <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
                <form action="//peterjacksons.us10.list-manage.com/subscribe/post?u=b53eaaa26571f5d0f5866e96f&amp;id=db1f8d9c17" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate mailchimp" target="_blank" novalidate>
                    <div id="mc_embed_signup_scroll">
                        <div class="mailchimp__input-wrap">
                            <input type="email" value="" name="EMAIL" class="mailchimp__input" id="mce-EMAIL" placeholder="Email Address">
                        </div>
                        <div class="mailchimp__input-wrap">
                            <input type="text" value="" name="FNAME" class="mailchimp__input" id="mce-FNAME" placeholder="First Name">
                        </div>
                        <div id="mce-responses" class="clear">
                            <div class="response" id="mce-error-response" style="display:none"></div>
                            <div class="response" id="mce-success-response" style="display:none"></div>
                        </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b53eaaa26571f5d0f5866e96f_db1f8d9c17" tabindex="-1" value=""></div>
                        <div class="clea mailchimp__input-wrapr"><input type="submit" value="SIGN UP" name="SIGN UP" id="mc-embedded-subscribe" class="button mailchimp__submit"></div>
                    </div>
                </form>
            </div>
            <!--End mc_embed_signup-->
        </div>
    </div>
</div>
<div class="page-footer__lower">
<div class="page-footer__lower-wrapper">
    <div class="page-footer__linkbox page-footer__comodo">
        <script language="JavaScript" type="text/javascript">
//            TrustLogo("https://www.peterjacksons.com/skin/frontend/peter_jackson_new/may2015/images/comodo_secure_seal_113x59_transp.png", "CL1", "none");
        </script>
        <a href="https://ssl.comodo.com" id="comodoTL">Comodo SSL</a>
        <a class="comodoimg" href="https://ssl.comodo.com/ev-ssl-certificates.php" id="comodoTL">EV SSL Certificate</a>
        <img class="confidence" src="<?php echo $this->getSkinUrl('images/shop-confidence.png'); ?>"/>
    </div>
    <div class="page-footer__linkbox page-footer__copyright">
        <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
    </div>
    <div class="page-footer__linkbox page-footer__social-icons">
        <ul class="page-footer__social-icons-ul">
            <li><a href="https://www.facebook.com/peterjacksonmenswear" target="_blank" class="page-footer__icon page-footer__icon--fb"></a></li>
            <li><a href="https://instagram.com/peterjacksonau/" target="_blank" class="page-footer__icon page-footer__icon--instagram"></a></li>
            <li><a href="https://twitter.com/peterjacksonau/" target="_blank" class="page-footer__icon page-footer__icon--twitter"></a> </li>
            <li><a href="https://www.youtube.com/channel/UCXtqKhYVVReUHY9C8KLQTIA/" target="_blank" class="page-footer__icon page-footer__icon--yt"></a></li>
            <li><a href="http://pinterest.com/peterjacksonau/" target="_blank" class="page-footer__icon page-footer__icon--pintrest"></a></li>
        </ul>
    </div>
</div>
</div>