<?php
    /** @var Magento\Framework\App\ObjectManager $objectManager */
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    /** @var PandaGroup\GuestWishlist\Helper\Data $guestWishlistHelper */
    $guestWishlistHelper = $objectManager->get('PandaGroup\GuestWishlist\Helper\Data');
?>

<li><a href="<?php echo $guestWishlistHelper->getListUrl() ?>"><?php echo __('My wishlist') ?></a></li>
