<?php

// @codingStandardsIgnoreFile

?>
<div class="after-items">
    <div class="after-items__top">
        <?php echo $block->getChildHtml('checkout.cart.minisummary') ?>
    </div>
    <div class="after-items__left">
        <?php echo $block->getChildHtml('coupon') ?>
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="after-items__right">
    <?php echo $block->getChildHtml('checkout.cart.methods.bottom2') ?>
    </div>
</div>