<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form class="cart-container__form"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
    >
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart-container__items-table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <div class="items-table" id="shopping-cart-table">
            <div class="items-table__row items-table__row--header">
                    <div class="items-table__column items-table__column--remove"></div>
                    <div class="items-table__column items-table__column--item"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></div>
                    <div class="items-table__column items-table__column--qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></div>
                    <div class="items-table__column items-table__column--size"><span><?php /* @escapeNotVerified */ echo __('Size') ?></span></div>
                    <div class="items-table__column items-table__column--price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></div>
                </div>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </div>
    </div>


    <div class="cart-container__actions">
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>


<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

