<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Link */
?>
<div class="header-right__wishlist" data-bind="scope: 'wishlist'">
    <a class="header-right__url-block" <?php /* @escapeNotVerified */ echo $block->getLinkAttributes() ?>>
        <!-- ko if: wishlist().counter -->
        <i class="header-right__wishlist-icon header-right__wishlist-icon--counter filtered-on-header"></i>
        <span data-bind="text: wishlist().counter" class="header-right__counter filtered-on-header"></span>
        <!-- /ko -->
        <!-- ko if: !wishlist().counter -->
        <i class="header-right__wishlist-icon filtered-on-header"></i>
        <span data-bind="text: wishlist().counter" class="header-right__counter filtered-on-header"></span>
        <!-- /ko -->
    </a>
    <div class="wishlist-message">
        <div class="wishlist-message__inner">
            <span class="wishlist-message__text">
                Adding to Wishlist...
            </span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
