<?php
    /* @var $block \PandaGroup\EmailTester\Block\System\Config\SendEmailTemplateTest */
?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#send_email_template_test_span');

        jQuery('#send_email_template_test_button').click(function () {
            var email = jQuery('#pandagroup_emailtester_emailtester_basic_settings_email_text').val();
            var template = jQuery('#pandagroup_emailtester_emailtester_basic_settings_template_select').val();
            var params = {'email': email, 'template': template};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#send_email_template_test_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        resultStatus = json.done;

                        if (resultStatus == '1') {
                            collectSpan.find('.collected').show();
                            resultText = 'Success: '+json.message;
                        } else {
                            resultText = 'Error: '+json.message;
                        }
                    }
                    jQuery('#send_email_template_test_message_span').text(resultText);

                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="send_email_template_test_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="send_email_template_test_message_span"></span>
</span>