<section class="faq__wrapper">

    <h3 class="faq__title">What countries does Peter Jackson ship to?</h3>
    <div class="faq__content">
        We currently deliver to Australia with free standard shipping. Express post is available upon request at an
        additional cost.Shipping to New Zealand is available for $30 with the shipping payment arranged post transaction.
        <br> <br>
        For international shipping please contact us at <a href="mailto:sales@peterjacksons.com" target="_top">sales@peterjacksons.com</a>.
    </div>

    <h3 class="faq__title">How long does it take to ship my goods once purchased?</h3>
    <div class="faq__content">
        Orders can take between 3 – 5 business days to be dispatched. All orders are dispatched from our head office in
        Melbourne.
    </div>

    <h3 class="faq__title">How do I return or exchange an item?</h3>
    <div class="faq__content">
        If your Peter Jackson purchase does not meet your expectations, you can return the item in its original and unused
        condition, with tags attached, within 30 days of purchase.
        <br> <br>
        Returns and exchanges must be sent to our head office in order to be processed. Please ensure the garments are
        packed properly to prevent damage as they are your responsibility until they arrive at our office.
        <br> <br>
        Our returns/exchange address is:
        <br> <br>
        426 Johnston Street,<br>
        Abbotsford<br>
        Melbourne 3000
        <br> <br>
        It is recommended that you use a postal service that insures you for the value of the items you are returning or
        alternatively obtain proof of posting.
        <br> <br>
        Further information on the return process will also be provided in your order.
        <br> <br>
        Once approved, returns take 2 - 4 business days to process.
    </div>

    <h3 class="faq__title">Are Peter Jackson gift cards valid online?</h3>
    <div class="faq__content">
        You can redeem our physical &amp; e-gift cards online and at any Peter Jackson store Australia wide.
    </div>

    <h3 class="faq__title">How long do I have to use my Peter Jackson gift card?</h3>
    <div class="faq__content">
        Your Peter Jackson gift card is valid for 12 months from the date of purchase.
    </div>

    <h3 class="faq__title">Do you offer personal tailoring to online purchases?</h3>
    <div class="faq__content">
        We unfortunately cannot alter your online purchases before shipping them. However, to guarantee the perfect fit
        for you, we recommend bringing your garments to a Peter Jackson store so we may advise you on the recommended
        alterations.
    </div>

    <h3 class="faq__title">What are the payment methods Peter Jackson accepts?</h3>
    <div class="faq__content">
        We accept VISA, MasterCard, Amex and PayPal.
    </div>

    <h3 class="faq__title">How can I resolve a problem with my order?</h3>
    <div class="faq__content" style="display: none;">
        Please contact us online at <a href="mailto:sales@peterjacksons.com" target="_top">sales@peterjacksons.com</a> or
        by phone on 9415 6281 between 9 - 5pm Monday to Friday with any enquiries you may have and we’ll endeavour to
        get back to you as soon as possible.
        <br> <br>
        We are closed on weekends.
        <br> <br>
        Please ensure to include your order number when enquiring about an online order.
    </div>

    <h3 class="faq__title">How can I join the Peter Jackson team?</h3>
    <div class="faq__content">
        Please find all information pertaining to starting a career with Peter Jacksons <a href="{{store url="careers"}}">here</a>.
    </div>

    <h3 class="faq__title">How do I find out my suit size?</h3>
    <div class="faq__content">
        When it comes to measuring yourself for a suit please measure:
        <ul>
            <li>Your over-arm shoulder width from shoulder to shoulder.</li>
            <li>Your chest (run the tape measure around your body, underneath your arms)</li>
            <li>Measure your waist (where your pants normally sit) </li>
            <li>Measure your outseam (the outer-most leg of your pants, trailing down from your hip to your ankle)</li>
            <li>Measure your inseam (run the tape measure down the inside of the leg to a point near the middle of your foot)</li>
        </ul>
        <br>
        If you’re still unsure about your measurements, please feel free head into one of our stores to get your measurements taken.
    </div>

    <h3 class="faq__title">Short, Regular &amp; Long Suits Explained.</h3>
    <div class="faq__content">
        Our coat and pant length is based on height.
        <ul>
            <li>A short is generally used on people under 170cm, with sleeves up to 32 in.</li>
            <li>A regular is generally for people between 172cm and 180cm, with sleeves of 32-33 in.</li>
            <li>A long is generally for people between 182cm and 187cm, with sleeves of 34-36 in.</li>
        </ul>
    </div>
</section>