<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/about-us"> <img src="{{media url='wysiwyg/menublock-images/ABOUT-US.jpg'}}"
            alt="" /> </a></figure>
    <figure><a href="/our-mills"> <img src="{{media url='wysiwyg/menublock-images/MILLS-AND-PRODUCTION.jpg'}}"
            alt="" /> </a></figure>
    <figure><a href="/sustainability"> <img src="{{media url='wysiwyg/menublock-images/SUSTAINABILITY-updates.jpg'}}"
            alt="" /> </a></figure>
</section>
