<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/explore-new-arrivals.html"> <img src="{{media url="wysiwyg/menublock-images/NEW-COLLECTION-updates.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/mens-suits-1/formal-wear.html"> <img src="{{media url="wysiwyg/menublock-images/FORMAL-WEAR-updates.jpg"}}" alt=""
            /> </a></figure>
    <figure><a href="/mens-suits-1/seasonal-highlights.html"> <img src="{{media url="wysiwyg/menublock-images/SEASONAL-HIGHLIGHTS-updates.jpg"}}" alt=""
            /> </a></figure>
</section>