<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/about-us"> <img src="{{media url="wysiwyg/menublock-images/About-us-Tile.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/our-mills"> <img src="{{media url="wysiwyg/menublock-images/MILLS_PRODUCTION-Tile.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/sustainability"> <img src="{{media url="wysiwyg/menublock-images/Sustainability-Tile.jpg"}}"
            alt="" /> </a></figure>
</section>