<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/blog"> <img src="{{media url='wysiwyg/menublock-images/Blog-Tile-NAV.jpg'}}" alt="A Bit Of History" /> </a></figure>
    <figure><a href="/blog/new-flagship-canberra-cbd/"> <img src="{{media url='wysiwyg/menublock-images/60thstore.jpg'}}" alt="New Flagship Canberra" /> </a></figure>
    <figure></figure>
</section>