<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/made-to-measure"> <img src="{{media url='wysiwyg/menublock-images/MADE-TO-MEASURE-updates.jpg'}}" alt="" />
        </a></figure>
    <figure><a href="/made-to-measure"> <img src="{{media url='wysiwyg/menublock-images/Personal-tailoring-updates.jpg'}}"
            alt="" /> </a></figure>
    <figure><a href="/made-to-measure"> <img src="{{media url='wysiwyg/menublock-images/BOOK-AN-APPOINTMENT-updates.jpg'}}"
            alt="" /> </a></figure>
</section>