<section class="header-middle__block header-middle__block--3-column">
    <figure><a href="/clothing/shirts-1.html"> <img src="{{media url="wysiwyg/menublock-images/SHIRTS-updates.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/clothing/sports-jackets-1.html"> <img src="{{media url="wysiwyg/menublock-images/SPORTSJACKETS-updates.jpg"}}"
            alt="" /> </a></figure>
    <figure><a href="/clothing/mens-chinos.html"> <img src="{{media url="wysiwyg/menublock-images/CHINOS-updates.jpg"}}"
            alt="" /> </a></figure>
</section>