<h2>THANK YOU FOR SUBSCRIBING</h2>
Your inbox just got a whole lot better: You will now be the first to
know about new arrivals, exclusive sales and private events.<br /><br />

Now you have signed up to looking good… Take a look at some<br />
<a href="{{store direct_url='mens-suits-1.html'}}">suits</a>, <a href="{{store direct_url='clothing/business-shirts.html'}}">shirts</a> or <a href="{{store direct_url='mens-accessories.html'}}">ties</a>.
<br />
<input type="button" class="continue-button" value="continue shopping"><br />
<span class="small">Remember to add <strong>info@peterjacksons.com</strong> to your address book so our emails don’t get blocked.</span>