<div class="catalog-main__bottom-info">
    <h3>Men's Suits</h3>
    <p>
        No longer just an office standard, the contemporary suit explores a wider range of styles, patterns and palettes, making it a much more appealing option as an essential piece for the modern man's wardrobe.
        Modern styling options and the casualisation of the workforce have driven up the popularity of casual suiting, seeing many men look too much bolder and brighter features outside of the norm.
    </p>
    <p>
        See our collection of suits explore both classic and contemporary patterns, styled with a modern spin. While Checks remain the dominant focus for the man looking to bring a bolder look to the table,
        the rise of subversive textiles, such as subtle Stripes, Jacquards or texturally rich fabrics, begin to work their way into the mainstream. Windowpane and Prince of Wales Checks seek to dominate many men's wardrobe,
        with more intricate patterning and highlight colours are used to set their suit apart from the norm.
    </p>
    <p>
        Seasonally focused palettes grow in density as the modern man becomes more aware and invested in his personal style.
    </p>
</div>