<div class="menu-about">
<ul>
    <li class="about_us"><a href="{{store url='about_us'}}">Our story</a></li>
    <li class="our-design"><a href="{{store url='our-design'}}">Design</a></li>
    <li class="our-labels"><a href="{{store url='our-labels'}}">Our labels</a></li>
    <li class="our-mills"><a href="{{store url='our-mills'}}">Mills &amp; Productions</a></li>
    <li class="sustainability"><a href="{{store url='sustainability'}}">Sustainability</a></li>
</ul>
</div>
<? echo $this->getData('my_var'); ?>