<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<br />
<table class="shipment-track" style="margin: 30px auto;width: 60%;">
    <thead>
        <tr>
            <th style="width: 33%;background-color: #EBEBEB;font-size:17px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;padding: 10px 10px 5px 10px;"><?= /* @escapeNotVerified */  __('Shipped By:') ?></th>
            <th style="width: 33%;background-color: #EBEBEB;font-size:17px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;text-align: right;padding: 10px 10px 5px 10px;"><?= /* @escapeNotVerified */  __('Tracking Number:') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <tr>
            <td style="width: 33%;background-color: #EBEBEB;font-size:17px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:200;padding: 5px 10px 10px 10px;"><?= $block->escapeHtml($_item->getTitle()) ?></td>
            <td style="width: 33%;background-color: #EBEBEB;font-size:17px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:200;text-align: right;padding: 5px 10px 10px 10px;"><?= $block->escapeHtml($_item->getNumber()) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
