<?php
/**
 * Category Widget template
 *
 * @var $block \PandaGroup\CategoryWidget\Block\Category\Widget
 * @var $stickyLabelsBlock PandaGroup\StickyLabels\Block\ListProduct\Labels
 * @var $discountBlock PandaGroup\DiscountBanner\Block\Category\Banner
 */
?>
<?php
    $productCollection = $block->getProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php
    $stickyLabelsBlock = $block->getChildBlock('category_widget_sticky_labels');
    $discountBlock = $block->getChildBlock('category_widget_discount_sticky_label');
    if (false !== $stickyLabelsBlock) {
        $canShowStickyLabels = $stickyLabelsBlock->getStickyLabelsOnProductStatus();
    } else {
        $canShowStickyLabels = false;
    }
?>

<?php if (null !== $productCollection AND true === $block->getCategoryWidgetStatus() AND $productCollection->count()): ?>

<section class="widget__slider">
    <h2 class="widget__slider-title"><?php echo $block->getCategoryWidgetLabel(); ?></h2>
    <h3 class="widget__slider-subtitle"><?php echo $block->getCategoryWidgetAdditionalLabel(); ?></h3>
    <div class="widget__slider-wrapper">
        <?php //echo $block->getAdditionalHtml() ?>
        <?php
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper grid products-grid">
            <?php $iterator = 1; ?>
            <ol class="widget__slider-container products list items product-items" data-mage-init='{"PandaGroup_CategoryWidget/js/slickInit": {"slidesToShow":"3"}}'>
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($productCollection as $_product): ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="widget__slider-item item product product-item">' : '</li><li class="widget__slider-item item product product-item">' ?>
                    <div class="slider__item product-item-info" data-container="product-grid">
                        <div class="slider__product-labels">
                            <?php if ($canShowStickyLabels): ?>
                                <?php if($_product->getIsMarked()): ?>
                                    <div class="product__sticky-label product__sticky-label--marked">Tipp</div>
                                <?php endif; ?>
                                <?php if($_product->getIsNew()): ?>
                                    <div class="product__sticky-label product__sticky-label--new">Neu</div>
                                <?php endif; ?>
                                <?php if(false !== $discountBlock): ?>
                                    <?php if (true === $discountBlock->getDiscountBannerShowProductInfoStatus()): ?>
                                        <?php $discountedProducts = $discountBlock->getDiscountMatchingProducts(); ?>
                                        <?php if(isset($discountedProducts[$_product->getId()]) AND true === $discountedProducts[$_product->getId()][1]): ?>
                                            <div class="product__sticky-label product__sticky-label--discount"><?= $discountBlock->getDiscountInformation(); ?></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>

                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="slider__item-box product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <a class="slider__item-name -product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                            <div class="slider__item-description product-item-description">
                                <?php if (true === $block->getCategoryWidgetShowDescriptionStatus()): ?>
                                    <?= /* @escapeNotVerified */ $_product->getCategoryWidgetDescription(); ?>
                                <?php endif; ?>
                            </div>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        </div>
                    </div>
                    <?= ($iterator == count($productCollection)+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>
