<div id="category-desc-box" class="about-block">
    <div class="about-block__image"><img src="{{view url='wysiwyg/about-us/about-top01_1.jpg'}}" alt="" /></div>
    <div class="about-block__text">
        <h1>Get to know us</h1>
    </div>
</div>
<div class="menu-about">
    <ul class="<? echo $this->getData('active-li'); ?>">
        <li class="about_us"><a href="<?php echo $block->getUrl('about_us') ?>">Our story</a></li>
        <li class="our-design"><a href="<?php echo $block->getUrl('our-design') ?>">Design</a></li>
        <li class="our-labels"><a href="<?php echo $block->getUrl('our-labels') ?>">Our labels</a></li>
        <li class="our-mills"><a href="<?php echo $block->getUrl('our-mills') ?>">Mills &amp; Productions</a></li>
        <li class="sustainability"><a href="<?php echo $block->getUrl('sustainability') ?>">Sustainability</a></li>
    </ul>
</div>
