<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php /** @var \Amasty\Shopby\Block\Navigation\State $block */?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="layered-nav__row">
        <h6 class="layered-nav__filter-header">Refine</h6>
        <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear layered-nav__clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
    </div>
    <div class="filter-current" id="am_shopby_container" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <ol class="items">
            <?php foreach ($_filters as $_filter): ?>
                <?php $filterSetting = $this->getFilterSetting($_filter->getFilter());?>
                <li class="item am_shopby_state_container layered-nav__active-filter"
                    data-container="<?php echo /* @escapeNotVerified */ $_filter->getFilter()->getRequestVar() ?>"
                    data-value="<?php /* @escapeNotVerified */ echo $_filter->getValueString();?>"
                >
                    <div>
                        <span class="filter-label"><?php /* @escapeNotVerified */ echo $block->escapeHtml(__($_filter->getName())); ?></span>
                        <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->viewLabel($_filter);?></span>
                    </div>
                    <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                    if ($clearLinkUrl):
                        ?>
                        <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                        </a>
                        <a class="action remove"
                           title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                            <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    <?php else: ?>
                        <a class="action remove" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                            <span>X</span>
                        </a>
                    <?php endif; ?>

                </li>
            <?php endforeach; ?>
        </ol>
        <script type="text/x-magento-init">
{
    "#am_shopby_container": {
        "amShopbyFilterContainer": {
                "collectFilters": <?php echo $block->collectFilters(); ?>
           }
    }
}

        </script>
    </div>
<?php endif; ?>
