<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue): ?>
    <?php if ($_attributeType === 'detailed_info'): ?>
        <div class="product attribute <?php /* @escapeNotVerified */ echo $_className?> product-main__description-wrapper">
    <?php else: ?>
        <div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
    <?php endif; ?>
    <?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
        <div class="value product-main__description-content" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>>
            <?php /* @escapeNotVerified */ echo $_attributeValue; ?>
        </div>
        <?php if ($_attributeType === 'detailed_info'): ?>
            <div class="product-main__description-image">
                <?php
                $productImageAttr = $_product->getCustomAttribute($_code . '_img');
                if (null !== $productImageAttr) {
                    $productImage = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'description_img');
                    $productImage->setImageFile($productImageAttr->getValue());
                    ?>
                    <img src="<?php echo $productImage->getUrl() ?>" alt="<?php echo $block->escapeHtml($_product->getTitle()) ?>" />
                    <?php
                }
                ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
