<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <section class="product-content__tabs">
                <?php foreach ($detailedInfoGroup as $name): ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>

                    <div class="data item title"
                         aria-labeledby="tab-label-<?php /* @escapeNotVerified */
                         echo $alias; ?>-title"
                         data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */
                    echo $alias; ?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?php /* @escapeNotVerified */
                           echo $alias; ?>"
                           id="tab-label-<?php /* @escapeNotVerified */
                           echo $alias; ?>-title">
                            <?php /* @escapeNotVerified */
                            echo $label; ?>
                        </a>
                    </div>

                <?php endforeach; ?>
            </section>
            <?php foreach ($detailedInfoGroup as $name): ?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item content" id="<?php /* @escapeNotVerified */
                echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */
                    echo $html; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<section data-bind="scope: 'sizeChart'" class="size-chart" id="size-chart">
<h2 data-bind="text: currentTab"></h2>
<section class="size-chart__tabs">
    <a href="#chart-suits" data-bind="click: changeCurrentTab">Suits</a>
    <a href="#chart-shirts" data-bind="click: changeCurrentTab">Shits</a>
    <a href="#chart-accessories" data-bind="click: changeCurrentTab">Suits</a>
    <a href="#chart-shoes" data-bind="click: changeCurrentTab">Shoes</a>
</section>
<section class="size-chart__section" data-bind="visible: isVisibleChart('chart-suits')">
    <div class="suit-label-chart label-chart">
        <section class="chart-row">
            <div class="size-wrap">
                <h4 class="size-chart__title">Suit size guide</h4>
                <table class="mceItemTable">
                    <tbody>
                    <tr class="res-name">
                        <td>Chest</td>
                    </tr>
                    <tr>
                        <td class="txt line1">Chest</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="hideit line3">&nbsp;</td>
                        <td>88</td>
                        <td>92</td>
                        <td>96</td>
                        <td>100</td>
                        <td>104</td>
                        <td>108</td>
                        <td>112</td>
                        <td>116</td>
                    </tr>
                    <tr>
                        <td class="line1">&nbsp;</td>
                        <td class="txt line2">(Inches)</td>
                        <td class="hideit line3">&nbsp;</td>
                        <td>34</td>
                        <td>36</td>
                        <td>38</td>
                        <td>40</td>
                        <td>42</td>
                        <td>44</td>
                        <td>46</td>
                        <td>48</td>
                    </tr>
                    </tbody>
                </table>
                <table class="double mceItemTable">
                    <tbody>
                    <tr class="res-name">
                        <td>Sleeve</td>
                    </tr>
                    <tr>
                        <td class="txt line1">Sleeve</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="txt line3">Short</td>
                        <td>42</td>
                        <td>43</td>
                        <td>44</td>
                        <td>45</td>
                        <td>46</td>
                    </tr>
                    <tr>
                        <td class="line1">&nbsp;</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="txt line3">Regular</td>
                        <td>45</td>
                        <td>46</td>
                        <td>47</td>
                        <td>48</td>
                        <td>49</td>
                    </tr>
                    </tbody>
                </table>
                <table class="double mceItemTable">
                    <tbody>
                    <tr class="res-name">
                        <td>Back Seam</td>
                    </tr>
                    <tr>
                        <td class="txt line1">Back Seam</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="txt line3">Short</td>
                        <td>68</td>
                        <td>69</td>
                        <td>70</td>
                        <td>71</td>
                        <td>72</td>
                    </tr>
                    <tr>
                        <td class="line1">&nbsp;</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="txt line3">Regular</td>
                        <td>70</td>
                        <td>72</td>
                        <td>73</td>
                        <td>74</td>
                        <td>75</td>
                    </tr>
                    </tbody>
                </table>
                <div class="size-note">
                    <table class="mceItemTable">
                        <tbody>
                        <tr>
                            <td class="bold">Chest</td>
                            <td>Measure at fullest part of the body</td>
                        </tr>
                        <tr>
                            <td class="bold">Sleeve Length</td>
                            <td>With arm bent at 90, measure from the middle of the neck across the shoulder and down to
                                the wrist.
                            </td>
                        </tr>
                        <tr>
                            <td class="bold">Back Seam</td>
                            <td>Measure from the start of your neck down to your natural waistline.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="suit-model"><br></div>
        </section>
        <hr>
        <section class="chart-row">
            <div class="size-wrap">
                <h4 class="size-chart__title">Trousers</h4>
                <table class="mceItemTable">
                    <tbody>
                    <tr class="res-name">
                        <td>Trousers</td>
                    </tr>
                    <tr>
                        <td class="txt line1">Waist</td>
                        <td class="txt line2">(Cm)</td>
                        <td class="hideit line3">&nbsp;</td>
                        <td>76</td>
                        <td>80</td>
                        <td>84</td>
                        <td>88</td>
                        <td>92</td>
                        <td>96</td>
                        <td>100</td>
                        <td>104</td>
                    </tr>
                    <tr>
                        <td class="line1">&nbsp;</td>
                        <td class="txt line2">(Inches)</td>
                        <td class="hideit line3">&nbsp;</td>
                        <td>28</td>
                        <td>30</td>
                        <td>32</td>
                        <td>34</td>
                        <td>36</td>
                        <td>38</td>
                        <td>40</td>
                        <td>42</td>
                    </tr>
                    </tbody>
                </table>
                <div class="size-note">
                    <table class="mceItemTable">
                        <tbody>
                        <tr>
                            <td class="bold">Waist</td>
                            <td>Measure around body at hip height</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="trousers-model"><br></div>
        </section>

    </div>
</section>
<section class="size-chart__section" data-bind="visible: isVisibleChart('chart-shirts')">
    <div class="shirts-label-chart label-chart">

        <h4 class="size-chart__title">Shirts size guide<span>(Sizes in cm)</span></h4>
        <div class="size-wrap">
            <table class="mceItemTable">
                <tbody>
                <tr class="res-name">
                    <td>Chest</td>
                </tr>
                <tr class="tr-heading">
                    <td>Size</td>
                    <td>Neck</td>
                    <td>Check</td>
                    <td>Shoulder</td>
                    <td>Sleeve</td>
                </tr>
                <tr>
                    <td>S</td>
                    <td>37</td>
                    <td>100</td>
                    <td>45</td>
                    <td>61</td>
                </tr>
                <tr>
                    <td>S</td>
                    <td>38</td>
                    <td>104</td>
                    <td>46</td>
                    <td>61</td>
                </tr>
                <tr>
                    <td>M</td>
                    <td>39</td>
                    <td>108</td>
                    <td>47</td>
                    <td>63.5</td>
                </tr>
                <tr>
                    <td>M</td>
                    <td>40</td>
                    <td>110</td>
                    <td>48</td>
                    <td>63.5</td>
                </tr>
                <tr>
                    <td>L</td>
                    <td>41</td>
                    <td>114</td>
                    <td>49</td>
                    <td>65</td>
                </tr>
                <tr>
                    <td>L</td>
                    <td>42</td>
                    <td>118</td>
                    <td>50</td>
                    <td>65</td>
                </tr>
                <tr>
                    <td>XL</td>
                    <td>43</td>
                    <td>122</td>
                    <td>51</td>
                    <td>66.5</td>
                </tr>
                <tr>
                    <td>XL</td>
                    <td>44</td>
                    <td>126</td>
                    <td>52</td>
                    <td>66.5</td>
                </tr>
                <tr>
                    <td>2XL</td>
                    <td>45</td>
                    <td>130</td>
                    <td>53</td>
                    <td>68</td>
                </tr>
                <tr>
                    <td>2XL</td>
                    <td>46</td>
                    <td>134</td>
                    <td>54</td>
                    <td>68</td>
                </tr>
                <tr>
                    <td>3XL</td>
                    <td>48</td>
                    <td>142</td>
                    <td>56</td>
                    <td>69.5</td>
                </tr>
                </tbody>
            </table>
            <div class="size-note">
                <table class="mceItemTable">
                    <tbody>
                    <tr>
                        <td class="bold">Neck</td>
                        <td>Measure around base of neck</td>
                    </tr>
                    <tr>
                        <td class="bold">Chest</td>
                        <td>Measure at fullest part of the body</td>
                    </tr>
                    <tr>
                        <td class="bold">Shoulder</td>
                        <td>Measure across shoulder at back</td>
                    </tr>
                    <tr>
                        <td class="bold">Sleeve length</td>
                        <td>With arm bent at 90, measure from the middle of the neck across the shoulder and down to the
                            wrist.
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="shirts-model"><br></div>
    </div>
</section>
<section class="size-chart__section" data-bind="visible: isVisibleChart('chart-accessories')">
    <div class="accessories-label-chart label-chart">

        <h4 class="size-chart__title">Accessories</h4>
        <div class="size-wrap">
            <table class="mceItemTable">
                <thead>
                <tr>
                    <td>Belts</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </thead>
                <tbody>
                <tr class="res-name">
                    <td>Accessories</td>
                </tr>
                <tr class="tr-heading">
                    <td class="txt line1">Size (Cm)</td>
                    <td>80/32</td>
                    <td>85/34</td>
                    <td>90/36</td>
                    <td>95/38</td>
                    <td>100/40</td>
                    <td>105/42</td>
                    <td>110/44</td>
                </tr>
                <tr>
                    <td class="line1">Waist (cm)</td>
                    <td>78-85</td>
                    <td>80-90</td>
                    <td>85-95</td>
                    <td>90-100</td>
                    <td>95-105</td>
                    <td>100-110</td>
                    <td>105-115</td>
                </tr>
                <tr>
                    <td class="line1">Waist (inch)</td>
                    <td>33</td>
                    <td>35</td>
                    <td>37</td>
                    <td>39</td>
                    <td>41</td>
                    <td>43</td>
                    <td>45</td>
                </tr>
                </tbody>
            </table>
            <table class="double mceItemTable">
                <thead>
                <tr>
                    <td>Socks</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </thead>
                <tbody>
                <tr class="res-name">
                    <td>Socks</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="txt line1">Size</td>
                    <td>8 - 12</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</section>
<section class="size-chart__section" data-bind="visible: isVisibleChart('chart-shoes')">
    <div class="shoes-label-chart label-chart">

        <h4 class="size-chart__title">Shoes</h4>
        <div class="size-wrap">
            <table class="mceItemTable">
                <tbody>
                <tr class="res-name">
                    <td>Shoes</td>
                </tr>
                <tr class="tr-heading">
                    <td>UK</td>
                    <td>US</td>
                    <td>EU</td>
                    <td>LENGTH</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>6</td>
                    <td>39</td>
                    <td>24.5 cm</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>7</td>
                    <td>40</td>
                    <td>25.4 cm</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>8</td>
                    <td>41</td>
                    <td>26.2 cm</td>
                </tr>
                <tr>
                    <td>8</td>
                    <td>9</td>
                    <td>42</td>
                    <td>27.1 cm</td>
                </tr>
                <tr>
                    <td>9</td>
                    <td>10</td>
                    <td>43</td>
                    <td>27.9 cm</td>
                </tr>
                <tr>
                    <td>10</td>
                    <td>11</td>
                    <td>44</td>
                    <td>28.6 cm</td>
                </tr>
                <tr>
                    <td>11</td>
                    <td>12</td>
                    <td>45</td>
                    <td>29.6 cm</td>
                </tr>
                <tr>
                    <td>12</td>
                    <td>13</td>
                    <td>46</td>
                    <td>30.5 cm</td>
                </tr>
                </tbody>
            </table>
            <div class="size-note">
                <table class="mceItemTable">
                    <tbody>
                    <tr>
                        <td>Measure your foot from one tip to the other. If after measuring your foot and consulting the table you find that you are between two sizes, you must opt for the larger size.</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="foot-model"></div>
    </div>
</section>
</section>


<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "sizeChart": {
                            "component": "sizeChart"
                        }
                    }
                }
            }
        }
</script>