<div class="field note">
    <label class="label" for="note"><span><?php /* @escapeNotVerified */ echo __('Note') ?></span></label>
    <div class="control">
        <input type="text" name="note" value="<?php echo $block->getNoteValue() ?>" title="<?php /* @escapeNotVerified */ echo __('Note') ?>" id="note" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Enter a note') ?>">
    </div>
</div>