<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="product-options-bottom">
    <?php echo $block->getChildHtml('', true);?>
    <div class="product-info-main__free-delivery">
        <strong>Free Delivery*</strong>
        <span>Applies to orders $100 or more. 30 day returns </span><span class="product-info-main__free-delivery-trigger">See details</span>
    </div>
</div>
