<?php

/**
 * @var $block \MagicToolbox\Magic360\Block\Html\Head
 */

if (!$block->isVisibile()) return;

$jsUrl = $block->getViewFileUrl('MagicToolbox_Magic360::js/magic360.js');
$jsPath = dirname($jsUrl);
$cssUrl = $block->getViewFileUrl('MagicToolbox_Magic360::css/magic360.css');
$cssPath = dirname($cssUrl);

$tool = $block->magicToolboxHelper->getToolObj();
$tool->params->resetProfile();

$headers = $tool->getHeadersTemplate($jsPath, $cssPath);

//NOTE: fix to support 'Minify JavaScript/CSS Files' options
if(preg_match('#\.min\.css$#', $cssUrl)) {
    $headers = preg_replace('#\.css\b#', '.min.css', $headers);
}
if(preg_match('#\.min\.js$#', $jsUrl)) {
    $headers = preg_replace('#\.js\b#', '.min.js', $headers);
}

echo $headers;
