<article class="page404">
    <h1>Whoops, our bad...</h1>
    <br>
    The page you requested was not found, and we have a fine guess why.<br><br>
    If you typed the URL directly, please make sure the spelling is correct.<br>
    If you clicked on a link to get here, the link is outdated.<br><br>
    What can you do?<br><br>
    Have no fear, help is near! There are many ways you can get back on track with Magento Store.<br><br>
    <a onclick="history.go(-1); return false;" href="#">Go back</a> to the previous page.<br>
    Use the search bar at the top of the page to search for your products.<br>
    Follow these links to get you back on track!<br>
    <a href="/">STORE HOME</a> | <a href="/customer/account/">MY ACCOUNT</a>
</article>