<article class="about-us">
    <section class="menu-about">
        {{widget type="Magento\Cms\Block\Widget\Block" template="Light4website_Cms::menu.phtml" block_id="about-us-menu"}}
    </section>
    <section class="about-us-wrapper about-us-wrapper--990">
        <h1 class="about-us-wrapper__title about-us-wrapper__title--opening">About Us</h1>
        <div class="about-us-wrapper__text-box about-us-wrapper__text-box--centered about-us-wrapper__text-box--770">
            <p>Peter Jackson is an Australian garment maker constructing quality menswear with a passion for innovative design and a strong emphasis on revolutionising the menswear retail space. We recognise there’s a huge disparity between ‘disposable fashion’ and luxury garments in both quality and price; we stand to bridge that gap because we believe that fashion and luxury should be accessible to everyone.</p>
            <p>By challenging modern day fashion conventions and pushing boundaries, we believe the modern man deserves clothing constructed from the world’s best textiles without paying over the odds. Our brand is not only a testament to authentic craftsmanship but also represents our dedication to instilling confidence in men to embrace their fashion aspirations whilst making confident and lasting impressions.</p>
        </div>
    </section>
    <section class="about-us-wrapper about-us-wrapper--no-padding">
        <img class="about-us-wrapper__fullwidth-image" src="{{view url='img/assets/brand/about-us-banner.png}}">
    </section>
    <section class="about-us-wrapper about-us-wrapper--1550 about-us-wrapper--where-it-all-began">
        <div class="about-us-wrapper__text-box">
            <div class="about-us-wrapper__wiab-box about-us-wrapper__wiab-box--left"><img src="{{view url='img/assets/brand/about-us-peter.jpg}}" /></div>
            <div class="about-us-wrapper__wiab-box about-us-wrapper__wiab-box--right">
                <h1 class="about-us-wrapper__title">Where it all began</h1>
                <p>Peter Jackson’s passion for tailoring and high quality fabrics began in 1948 in the retail heart of Melbourne’s CBD on Little Bourke Street. When siblings Olga, Peter and David Jackson opened their first barbershop, they had no inclination that their humble hairstyling ambitions would develop into an iconic Australian fashion institution.</p>
                <p>The barbershop also sold ties and despite their success in styling hair, it soon became apparent to the trio that their penchant for panache could be better applied to fashion. Their modest line of ties gradually evolved into a full tailored men’s range and Peter Jackson promptly established itself as the number one destination for distinguishing men’s fashion in Melbourne.</p>
                <p>Over 60 years and three generations later, Peter Jackson’s approach has never been more focused. As our brand continues to grow nationally, so does our dedication to providing, luxury, innovation and excellence tailored to meet every man’s needs.</p>
                <p>Never compromising quality for cost, our garments continue to be constructed from world-class European textiles that transcend traditional menswear by placing a focused emphasis on offering elegant attire that’s attainable for every man.</p>
                <p>With a new generation of Jacksons at the helm and 40 stores now open Australia wide, Peter Jackson still remains a privately owned family business maintaining and implementing the ideals and values our brand’s fashion foundations were built on.</p>
            </div>
    </section>
</article>
