<section class="elevate">
    <div class="elevate__header">
        <div class="elevate__wrapper">
            <div class="elevate__box">
                <p class="elevate__title">Elevate Your Style</p>
                <p class="elevate__para">Celebrating the ethos of independence and divergence from trend based culture,
                    this season we are inspired by leaders of industry and those that cut their own path, both in their
                    professional and personal lives.</p>
                <p class="elevate__para">Designed to meet the demands of the professional pathfinder, the AW18 collection
                    unites artisan craftsmanship with naturally resilient wool, cashmere and cotton fabrics, creating a
                    stalwart range of seasonless staples.</p>
                <p class="elevate__para elevate__para--last">Woven into gripping patterns in understated palettes, the range celebrates modern
                    simplicity, with softer silhouettes and tactile fabrics imbued into tailoring that reflects confidence
                    and comfort in one's own skin.</p>
            </div>
        </div>
    </div>
</section>

<section class="elevate-images">
    <div class="elevate-images__wrapper">
        <div class="elevate-images__box--left">
            <img src="{{view url='img/assets/elevate-your-style/men-suit.png'}}">
        </div>
        <div class="elevate-images__box--right">
            <p class="elevate-images__title">Creature</p>
            <p class="elevate-images__title elevate-images__title--small">COMFORTS</p>
            <p class="elevate-images__sub-title">Made from naturally resilient wool, explore our new collection of
                soft-tailored suits designed to comfortably transition into Autumn.
                <button class="btn" onclick="location.href='/mens-suits-1.html'">Shop Suits</button>
            </p>
        </div>
        <div class="tactile-tailoring">
            <div class="tactile-tailoring__wrapper">
                <div class="tactile-tailoring__box">
                    <p class="tactile-tailoring__title">Tactile</p>
                    <p class="tactile-tailoring__title tactile-tailoring__title--small">Tailoring</p>
                    <p class="tactile-tailoring__sub-title">Our new collection of seasonless staples are made from wider
                        weaves for textured, more breathable garment.
                        <button class="btn btn--white" onclick="location.href='/mens-blazers.html'">Shop Jackets</button>
                    </p>
                </div>
            </div>
        </div>
        <div class="shirt-fronting">
            <div class="elevate-images__box--left">
                <img src="{{view url='img/assets/elevate-your-style/shirt.png'}}">
            </div>
            <div class="elevate-images__box--right">
                <p class="elevate-images__title">Shirt</p>
                <p class="elevate-images__title elevate-images__title--small">Fronting</p>
                <p class="elevate-images__sub-title">Designed for optimal performance, charge into the new season with
                    our lastest collection of corporate and casual shirts.
                    <button class="btn" onclick="location.href='/business-shirts.html'">Shop Shirts</button>
                </p>
            </div>
        </div>
        <div class="italian-job">
            <div class="italian-job__reverse">
                <img src="{{view url='img/assets/elevate-your-style/suit.png'}}">
                <div class="elevate-images__box--right italian-job__box">
                    <p class="elevate-images__title italian-job__title--small">The</p>
                    <p class="elevate-images__title italian-job__title--medium">Italian <span class="elevate-images__title italian-job__title--small">Job</span></p>
                    <p class="elevate-images__sub-title">Powerful pattern and uncompromising palettes, our new range of
                        five-fold ties are spun from the finest Italian silk.
                        <button class="btn" onclick="location.href='/ties.html'">Shop Silk Ties</button>
                    </p>
                </div>
            </div>
        </div>
        <div class="long-haul">
            <div class="elevate-images__box--left">
                <img src="{{view url='img/assets/elevate-your-style/bag.png'}}">
            </div>
            <div class="elevate-images__box--right long-haul__box">
                <p class="elevate-images__title italian-job__title--small italian-job__title--xsmall long-haul__nomargin">The</p>
                <p class="elevate-images__title italian-job__title--66">Long</p>
                <p class="elevate-images__title italian-job__title--99">Haul</p>
                <p class="elevate-images__sub-title">A robust collection of heavy-weight holdalls and document bags
                    designed to meet your work and weekend needs.
                    <button class="btn" onclick="location.href='/mens-bags.html'">Shop Bags</button>
                </p>
            </div>
        </div>

        {{block class="PandaGroup\CategoryWidget\Block\Category\Widget" template="PandaGroup_CategoryWidget::categorywidget.phtml"}}

    </div>
</section>

<script>
    require(["js/elevate"], function (elevate) {
        var elevateInit = elevate();
    });
</script>
