<section class="home-banner home-banner--header">
    <div class="home-banner--custom-wrapper">
        <div class="home-banner__right-box">
            <img src="{{view url='img/assets/home-11-2017/upto60.png'}}" class="home-banner__fixed-image" alt="High Stakes Spring Sale" onclick="location.href='/mens-suits-1.html'">

            <button class="btn btn--center btn--black" onclick="location.href='/mens-suits-1.html'">Shop Sale</button>
        </div>

        <a class="home-banner__scroll-down"></a>
    </div>
</section>

<section class="home-banner home-banner__formated-image home-banner__formated-image--gift" id="top">
    <div class="home-banner--wrapper home-banner--pos-right">
        <div class="home-banner__box--right">
            <p class="home-banner__title home-banner__title--gift">
                Man
                <span class="home-banner--space">/</span>
                Gift
                <span class="home-banner--space">/</span>
                Guide
            </p>
            <p class="home-banner__description--gift">
                Guarantee your gift giving prowess this Christmas.
            </p>

            <button class="btn btn--sm-padding btn--pos-right">Explore Gift Guide</button>
        </div>
    </div>
</section>

<section class="home-banner home-banner__formated-image home-banner__formated-image--bottom-secondary" onclick="location.href='/made-to-measure'">
    <div class="home-banner--wrapper home-banner--wrapper-left">
        <div class="home-banner__box home-banner__box-left">
            <p class="home-banner__title">
                Design your
                <span class="home-banner--br"></span>
                Own Suit
            </p>
            <p class="home-banner__description">
                Redefine modern tailoring and create a
                <span class="home-banner--br"></span>
                suit, unique to your sense of style.
            </p>

            <button class="btn btn--sm-padding" onclick="location.href='/made-to-measure'">Book Online</button>
        </div>
    </div>
</section>

<section class="home-banner home-banner__formated-image home-banner__formated-image--beard">
    <div class="home-banner--wrapper home-banner--wrapper-right">
        <div class="home-banner__box home-banner__box-centered home-banner__box-right">
            <p class="home-banner__title home-banner__title--black">
                NO BEARD &
                <span class="home-banner--br"></span>
                ready to grow?
            </p>
            <p class="home-banner__description home-banner__description--black">This December grow a beard, raise funds and help beat bowel cancer.</p>
            <button class="btn btn--sm-padding btn--black-hover" >Learn More</button>
        </div>
    </div>
</section>

<section class="men-guide">
    <div class="men-guide__header">
        <h1>Men's Guide</h1>
        <p>A guide to living and dressing well</p>
    </div>

    <div class="men-guide__boxes">
        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/spring-racing-guide.jpg'}}" alt="Spring Racing Guide" />
                                <div class="men-guide-slider__content">
                                    <h2 class="men-guide-slider__title">Derby Day Form Guide</h2>
                                    <p>Own monochrome &dominate Derby Day with our race day edit.</p>
                                    <a href="#" class="men-guide-slider__more">Read more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/dan_boat_angle.jpg'}}" alt="Dan Boat Angle" />
                                <div class="men-guide-slider__content">
                                    <h2 class="men-guide-slider__title">SS17: The New Wave</h2>
                                    <p>Go behind the scenes & read about the inspiration behind our campaign.</p>
                                    <a href="#" class="men-guide-slider__more">Read more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/Dan_light_windowpane_crop.jpg'}}" alt="Dan Light Windowpane Crop" />
                                <div class="men-guide-slider__content">
                                    <h1 class="men-guide-slider__title">A New Wave of Tailoring</h1>
                                    <p>Get the low down on our new Spring Summer collection.</p>
                                    <a href="#" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/derby-day.jpg'}}" alt="Derby Day" />
                                <div class="men-guide-slider__content">
                                    <h1 class="men-guide-slider__title">Why We Use Egyptian Cotton</h1>
                                    <p>Go behind the seams and see what makes our shirts so special.</p>
                                    <a href="#" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<script>
    require(["js/home"], function(home) {
        var homeInit = home();
    });
</script>