<section class="main-banner" onclick="location.href='/sale.html'">
    <div class="main-banner__wrapper">
        <div class="main-banner__inner">
            <div class="main-banner__content-box">
                <img src="{{view url='img/assets/home-11-2017/sale30off.png'}}" onclick="location.href='#'"/>
                <button class="btn btn--padding" onclick="location.href='/sale.html'">Shop Now</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--elevate" onclick="location.href='/discover-more-page'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero">
                    <p class="elevate">Elevate</p>
                    <p class="your-style">Your Style</p>
                </div>
                <div class="home-banner__header--mobile">
                    <p>Elevate Your Style</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Inspired by leaders of industry</p>
                    <p class="home-banner__text">& those that cut their own path.</p>
                </div>
                <button class="btn" onclick="location.href='/discover-more-page'">Discover More</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--tactile"
         onclick="location.href='/about-us.html'">
    <div class="home-banner__wrapper--end">
        <div class="home-banner__inner--end">
            <div class="home-banner__content-box home-banner__content-box--end">
                <div class="home-banner__header home-banner__header--end">
                    <p>the man who
                        <br>
                        started it all</p>
                </div>
                <div class="home-banner__text-box home-banner__text-box--none">
                    <p class="home-banner__text">Peter Jackson’s passion for tailoring began in 1948 in the retail heart of Melbourne’s CBD (Little Bourke Street)</p>
                    <p class="home-banner__text">As a modest barbershop, it also developed an interest in selling ties, and eventually evolved into the iconic brand it is today.</p>
                </div>
                <p class="home-banner__text-box--mobile">Peter Jackson 1973</p>
                <button class="btn" onclick="location.href='/about-us.html'">Learn More</button>
            </div>
        </div>
    </div>
</section>

{{block class="PandaGroup\CategoryWidget\Block\Category\Widget" template="PandaGroup_CategoryWidget::categorywidget.phtml"}}

<section class="home-banner home-banner__image home-banner__image--measure" onclick="location.href='/made-to-measure'">
    <button class="btn btn-measure" onclick="location.href='/made-to-measure'">Reserve Your Experience</button>
</section>

<section class="men-guide">
    <div class="men-guide__header">
        <h1>Men's Guide</h1>
        <p>A guide to living and dressing well</p>
    </div>

    <div class="men-guide__boxes">
        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/blog-tile-1.jpg'}}"
                                     alt="Read our guide on what to wear through Autumn." onclick="location.href='/blog'"/>
                                <div class="men-guide-slider__content">
                                    <h2 class="men-guide-slider__title">Transeasonal Tailoring</h2>
                                    <p>Read our guide on what to wear through Autumn.</p>
                                    <a href="/blog" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
<!--                    <div>-->
<!--                        <div class="men-guide-slider__slide">-->
<!--                            <div class="men-guide-slider__img">-->
<!--                                <img src="{{view url='img/assets/home-11-2017/support-decembeard.jpg'}}"-->
<!--                                     alt="Grow a Beard. Help Save Lives."/>-->
<!--                                <div class="men-guide-slider__content">-->
<!--                                    <h2 class="men-guide-slider__title">Grow a Beard. Help Save Lives.</h2>-->
<!--                                    <p>Beard up and help us raise awareness with Decembeard.</p>-->
<!--                                    <a href="#" class="men-guide-slider__more">Get Involved</a>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>

        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/blog-tile-2.jpg'}}"
                                     alt="From humble barber shop beginnings to 60 stores. See our new Canberra Flagship." onclick="location.href='/blog'"/>
                                <div class="men-guide-slider__content">
                                    <h1 class="men-guide-slider__title">The 60th Store Nationally</h1>
                                    <p>From humble barber shop beginnings to 60 stores. See our new Canberra Flagship.</p>
                                    <a href="/blog" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
<!--                    <div>-->
<!--                        <div class="men-guide-slider__slide">-->
<!--                            <div class="men-guide-slider__img">-->
<!--                                <img src="{{view url='img/assets/home-11-2017/derby-day.jpg'}}"-->
<!--                                     alt="Derby Day Form Guide"/>-->
<!--                                <div class="men-guide-slider__content">-->
<!--                                    <h1 class="men-guide-slider__title">Derby Day Form Guide</h1>-->
<!--                                    <p>Own monochrome &amp; dominate Derby Day with our race day edit.</p>-->
<!--                                    <a href="#" class="men-guide-slider__more">Learn more</a>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>

    </div>
</section>

<script>
    require(["js/home"], function (home) {
        var homeInit = home();
    });
</script>