<section class="main-banner">
    <div class="main-banner__wrapper">
        <div class="main-banner__inner">
            <div class="main-banner__content-box">
                <img src="{{view url='img/assets/home-11-2017/dec-pj-sale.png'}}" class="main-banner__logo" alt="Peter Jacksons Sale Up To 60%" onclick="location.href='/mens-suits-1.html'">
                <p class="main-banner__text">Up to 60% off</p>
                <button class="btn" onclick="location.href='/mens-suits-1.html'">Shop Sale</button>
            </div>
        </div>
    </div>

    <a class="main-banner__scroll-down"></a>
</section>

<section class="home-banner home-banner__image home-banner__image--gift" id="top">
    <div class="home-banner__wrapper home-banner__wrapper--right home-banner__wrapper--center">
        <div class="home-banner__box--gift">
            <p class="home-banner__title home-banner__title--gift">
                Man
                <span class="home-banner__slash">/</span>
                Gift
                <span class="home-banner__slash">/</span>
                Guide
            </p>
            
            <p class="home-banner__description--gift">
                Guarantee your gift giving prowess this Christmas.
            </p>

            <button class="btn btn-margin-top">Explore Gift Guide</button>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--measure">
    <div class="home-banner__wrapper home-banner__wrapper--left">
        <div class="home-banner__box">
            <p class="home-banner__title">
                Design your
                <br />
                Own Suit
            </p>
            <p class="home-banner__description">
                Redefine modern tailoring and create a
                <br />
                suit, unique to your sense of style.
            </p>
            <button class="btn btn-margin-top" onclick="location.href='/made-to-measure'">Book Online</button>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--beard">
    <div class="home-banner__wrapper home-banner__wrapper--right">
        <div class="home-banner__box--beard">
            <p class="home-banner__title--beard">
                No beard &
                <br />
                ready to grow?
            </p>
            <p class="home-banner__description--beard">
                This December grow a beard, raise funds and help beat bowel cancer.
            </p>
            <button class="btn btn-black" onclick="location.href='/made-to-measure'">Learn More</button>
            <div class="home-banner__logos">
                <img src="{{view url='img/assets/home-11-2017/decembeard_supp.png'}}"
                     alt="DecemBeard Supporting" title="DecemBeard Supporting">
                <img src="{{view url='img/assets/home-11-2017/bca.png'}}"
                     alt="Bowel Cancer Australia" title="Bowel Cancer Australia">
                <img src="{{view url='img/assets/home-11-2017/pj.png'}}"
                     alt="Peter Jackson" title="Peter Jackson">
            </div>
        </div>
    </div>
</section>

<section class="men-guide">
    <div class="men-guide__header">
        <h1>Men's Guide</h1>
        <p>A guide to living and dressing well</p>
    </div>

    <div class="men-guide__boxes">
        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/xmas-guide-blog.jpg'}}" alt="Men's Gift Guide" />
                                <div class="men-guide-slider__content">
                                    <h2 class="men-guide-slider__title">Men's Gift Guide</h2>
                                    <p>Perfect the art of gift giving with our fail-safe guide.</p>
                                    <a href="#" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/support-decembeard.jpg'}}" alt="Grow a Beard. Help Save Lives." />
                                <div class="men-guide-slider__content">
                                    <h2 class="men-guide-slider__title">Grow a Beard. Help Save Lives.</h2>
                                    <p>Beard up and help us raise awareness with Decembeard.</p>
                                    <a href="#" class="men-guide-slider__more">Get Involved</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="men-guide__boxes--half">
            <div class="men-guide-slider">
                <div class="men-guide-slider__slides slick-init">
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/linen-tailoring-guide.jpg'}}" alt="Light-weight Luxury" />
                                <div class="men-guide-slider__content">
                                    <h1 class="men-guide-slider__title">Light-weight Luxury</h1>
                                    <p>Read our guide on men's Summer linen tailoring.</p>
                                    <a href="#" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="men-guide-slider__slide">
                            <div class="men-guide-slider__img">
                                <img src="{{view url='img/assets/home-11-2017/derby-day.jpg'}}" alt="Derby Day Form Guide" />
                                <div class="men-guide-slider__content">
                                    <h1 class="men-guide-slider__title">Derby Day Form Guide</h1>
                                    <p>Own monochrome &amp; dominate Derby Day with our race day edit.</p>
                                    <a href="#" class="men-guide-slider__more">Learn more</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

<script>
    require(["js/home"], function(home) {
        var homeInit = home();
    });
</script>