<section class="look-book">
    <div class="look-book__slider">
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5ae54f11ae.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5aeb2ab2d3.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5aee5b64fa.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5aef842009.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5af2dc0cb9.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5af5d22cfa.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5af89d735b.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5af9c2240b.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5afc7df288.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5affe0f72d.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b03d861b9.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b06dae14e.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b096d9a70.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b0eecf13d.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b14a1ecb1.jpg'}}">
        </article>
        <article>
            <img class="look-book__img" src="{{media url='lookbookslider/1414X1000/58f5b1683fda2.jpg'}}">
        </article>
    </div>
</section>
<section class="look-book__progress">
    <div class="look-book__progress--inside"></div>
</section>

<script>
    require(["js/LookBook"], function(mod) {
        var LookBookInit = new mod.LookBook();
    })
</script>