<section class="made-to-measure">
    <section class="measure-top">
        <img class="measure-top__img" src="{{media url='wysiwyg/made-to-measure-logo.png'}}">
        <article class="measure-top__bg">
            <div class="measure-top__wrapper">
                <h2 class="measure-top__title">Our passion <i>Your style</i></h2>
                <p class="measure-top__paragraph">Whether you’re looking to elevate your work wear or simply have the
                    desire to design something truly
                    unique; the made-to-measure experience is your opportunity to fulfil all your sartorial aspirations.
                    Combining artisanal craft with complete creative freedom, each suit becomes a finely tailored
                    extension of the man that wears it, reflecting his tastes for quality and style.</p>
                <p class="measure-top__paragraph">Peter Jackson’s made-to-measure experience embodies our passion for
                    fine tailoring and our belief
                    that every man deserves the best.</p>
                <button onclick="location.href='{{store url='schedule-your-appointment'}}'"  class="measure-top__button">Book An Appointment</button>
                <figure class="measure-top__arrow"></figure>
            </div>
        </article>
    </section>
    <section class="measure-suit">
        <h2 class="measure-suit__title">The Suit</h2>
        <div class="measure-suit__row">
            <div class="measure-suit__column--text">
                <div class="measure-suit__text">
                    40 Styles TO <br>CHOOSE FROM
                </div>
                <div class="measure-suit__text">
                    CHOOSE YOUR <br>LAPELS
                </div>
                <div class="measure-suit__text">
                    single OR <br>double breast
                </div>
            </div>
            <div class="measure-suit__column--suit"></div>
            <div class="measure-suit__column--text">
                <div class="measure-suit__text">
                    70+ FABRICS <br>BY MARZOTTO
                </div>
                <div class="measure-suit__text">
                    5 WEEK <br>DELIVERY
                </div>
                <div class="measure-suit__text">
                    CUSTOM STITCHING<br>AND LINING
                </div>
            </div>
        </div>
    </section>
    <section class="measure-works">
        <div class="measure-works__wrapper">
            <h2 class="measure-works__title">How it works</h2>
            <p class="measure-works__paragraph">With up to 70+ fabrics developed with Marzotto to choose from and 30
                styles to customise, our made to measure
                experience gives you the freedom to create a suit that speaks to you and your sense of personal style.
                We give you the opportunity to customise every aspect of your suit to make it truly unique, from fabric
                to
                lapels to cuff and lining all the way down to the buttons.</p>
            <p class="measure-works__paragraph">From design to delivery, your suit will take 5 weeks to ensure that it
                meets our high standards and reflects
                your complete vision.</p>
            <p class="measure-works__paragraph--priced">Priced from $799 - $999</p>
        </div>
    </section>
    <section class="measure-slider">
        <div class="measure-slider__slide measure-slider__slide--1">
            <div class="measure-slider__wrapper">
                <span class="measure-slider__number">1</span>
                <h6 class="measure-slider__title">MEETING OF THE MINDS</h6>
                <p class="measure-slider__paragraph">Creating a made to measure suit is one of the most personalised
                    shopping experiences a man can achieve,
                    which is why we believe that it should be done face-to-face.</p>
                <p class="measure-slider__paragraph">The design consultation is arguably the most important part of our
                    made to measure experience. During
                    your
                    first session your individual tailor will guide you through our program, discussing all the options
                    available for creating your uniquely tailored garment. </p>
                <p class="measure-slider__paragraph">After you have been measured and your selections are
                    made, a design template is created.</p>

                <p class="measure-slider__paragraph--rwd">Your Made to Measure experience first starts with a meeting.
                    It is here that one of our specialists will help guide you through our program, customising and
                    creating a design blueprint unique to you.</p>
            </div>
        </div>
        <div class="measure-slider__slide measure-slider__slide--2">
            <div class="measure-slider__wrapper">
                <span class="measure-slider__number">2</span>
                <h6 class="measure-slider__title">CHOOSE YOUR STYLE</h6>
                <p class="measure-slider__paragraph">The made-to-measure experience is about creating a suit the speaks
                    to you and your sense of personal
                    style.
                    It all begins with the selection of the block; the core frame from which your suit will be built
                    around.
                </p>
                <p class="measure-slider__paragraph">Your choice here will govern the overall shape of your suit, with a
                    wide array of possibilities in both
                    double and single breasted cuts.</p>

                <p class="measure-slider__paragraph--rwd">Feeling comfortable in the style of your suit is just as
                    important as the size and fit.</p>
                <p class="measure-slider__paragraph--rwd">Selecting from our style guide, you’ll be able to completely
                    customise your suit, building up from several core looks.</p>
            </div>
        </div>
        <div class="measure-slider__slide measure-slider__slide--3">
            <div class="measure-slider__wrapper">
                <span class="measure-slider__number">3</span>
                <h6 class="measure-slider__title">SELECT YOUR FABRIC</h6>
                <p class="measure-slider__paragraph">Arguably the most important and personal step of the
                    made-to-measure experience is selecting the fabric
                    of
                    your suit. Partnered with Marzotto, one of the most prestigious mills in Italy. You can select from
                    a
                    diverse range of 70+ fabrics, milled from the purest Australian Merino wool.
                </p>
                <p class="measure-slider__paragraph--rwd">Selecting your fabric is an integral of creating an
                    individualised garment, which is why we offer a diverse selection of patterns and colours, all
                    sourced from the prestigious Marzotto mill in Italy.</p>
            </div>
        </div>
        <div class="measure-slider__slide measure-slider__slide--4">
            <div class="measure-slider__wrapper">
                <span class="measure-slider__number">4</span>
                <h6 class="measure-slider__title">PERSONALISATION</h6>
                <p class="measure-slider__paragraph">Customisation is the bedrock of our Made to Measure experience.
                    Once you’ve selected the suit style and
                    fabric you’ll be able to completely alter every aspect of your garment. Tweak and modify the form
                    and
                    fit of
                    the arm, pant or chest Nothing is off limits, introduce new elements like patch, flap or jet
                    pockets,
                    adjust
                    their angle and size or remove them entirely, From lapels to cuff, the potential for personalisation
                    is
                    limitless.</p>
                <p class="measure-slider__paragraph">We want you to create the garment of your dreams, whether it’s a
                    classic double breast with a bold Pin
                    Stripes tor a street style inspired minimalist black suit.</p>

                <p class="measure-slider__paragraph--rwd">The Made to Measure program gives you the unique opportunity
                    to take creative control over every aspect of the garment. From lapel to lining, you’ll have the
                    option to tweak or modify or remove as you see fit.</p>
            </div>
        </div>
        <div class="measure-slider__slide measure-slider__slide--5">
            <div class="measure-slider__wrapper">
                <span class="measure-slider__number">5</span>
                <h6 class="measure-slider__title">FINAL FITTING</h6>
                <p class="measure-slider__paragraph">Our made to measure program is the purest extension of our passion
                    for truly tailored garments. To ensure
                    the complete satisfaction with the fit and feel of your garment, we organise a final consultation.
                    Not
                    only does this give us the opportunity to make any final adjustments, should the need arise, but
                    also
                    ensures that you walk out our doors with a garment of unparalleled comfort and individuality.
                </p>

                <p class="measure-slider__paragraph--rwd">Made to measure is about getting the perfect fit for you.
                    After your garment is constructed and return to our store, you will be called in for a final fitting
                    to ensure complete sartorial satisfaction.</p>
            </div>
        </div>
    </section>
    <section class="measure-schedule">
        <div class="measure-schedule__wrapper">
            <h2 class="measure-schedule__title">SCHEDULE AN APPOINTMENT</h2>
            <p class="measure-schedule__paragraph">Our Made to Measure experience is tailored around you, from the
                choice of fabric and fit to the where and when of
                your first appointment. Book now to secure your spot with one of our Made to measure specialists and
                begin your
                Made to Measure experience.</p>
            <button class="measure-schedule__button" onclick="location.href='{{store url='schedule-your-appointment'}}'">BOOK YOUR FITTING</button>
        </div>
    </section>
</section>

<script>
    require(["js/MadeToMeasure"], function(mod) {
        var MadeToMeasureInit = new mod.MadeToMeasure();
    })
</script>