<div class="std">
    <h3>Returns</h3>

    <p>If, for reasons of Change of Mind, Faulty Product, or Incorrect Sizing, you would like to return your purchase
        to us, we would be more than happy to offer you an exchange or refund in accordance with the ACCC's consumer
        guarentees. Please find the conditions for Returns below:</p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>The products are unworn/unused
        and in resellable condition;</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>There are no alternations or
        modifications to the garment;</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Original packaging is in
        original condition;</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>The products have been in your
        possession for no longer than 30 days or what has been deemed a reasonable possession period.(therefore
        eliminating any transit time). </p>

    <p>Before a refund or exchange can be granted, all items will require an inspection from either a store manager or
        the Peter Jackson Head Office Team. We reserve the right to refuse a return if the above has not been adhered to.
    </p>
</div>

<div class="std">
    <h3>In-store refunds and exchanges</h3>

    <p>If you have purchased your garment online, you can choose to return or exchange your garment to any one of our
        stores (excluding DFO, Harbor Town and outlet stores). For exchanges, please contact your local Peter Jackson
        store to ensure it has the right garment available.</p>

    <p>Refunds are always performed using the method of payment. If you choose to return the garment in-store, please
        make sure you have your credit card that you made the online purchase with and that the card holder is present
        at the time of the return. This will enable the staff member to process the return/exchange for you. You will
        also need to take a printout of your Order Confirmation which is emailed to you at the time of online purchase,
        and your Delivery Docket which is included in your package. If you can’t print your Order Confirmation email you
        must bring along: a form of ID, the Delivery Docket and display their Order Confirmation email on a mobile device.
        If you no longer have your order confirmation, please be sure to provide a proof of purchase.</p>

    <p>In-store return & exchange policies apply. All conditions above are in addition to your statutory rights.</p>
</div>

<div class="std">
    <h3>Online refunds and exchanges</h3>

    <p>If you have purchased your garment online, you can choose to return or exchange all or individual purchases by
        mailing them to our head office, 426 Johnston St, Abbotsford, VIC 3067. Online returns must be adherent to our
        Returns Policy and be accompanied by your confirmation email, or, if not possible, a proof of purchase. Please
        also include a note with the reason for your return, detailing whether you are seeking an exchange or refund.</p>

    <p>A refund or exchange will be processed once the item is received and inspected at our head office. Once received
        and assessed, a customer service representative will contact you via email to inform you of the pending refund
        or expected duration of the exchange.</p>

    <p>Refunds are always performed using the method of payment and will be returned into the account used for Online Check Out.</p>

    <p>Return & exchange policies apply. Peter Jackson Australia Pty. reserves the right to not accept responsibility for
        mailing costs incurred for returns or exchanges to our Head Office, 426 Johnston St, Abbotsford, VIC 3067. All
        conditions above are in addition to your statutory rights.</p>
</div>

<div class="std">
    <h3>Outlet Store Refunds and Exchange</h3>

    <p>If you have purchased your garment at one of our Outlet Stores, refunds or exchanges can only be processed across
        our Outlet Store network.</p>

    <p>Peter Jackson will exchange or refund an item if faulty and proof of purchase can be provided. Change of Mind is
        only accepted for exchange or store credit and redeemable within 14 days of purchase. Returns must be adherent
        to our Returns Policy and be accompanied by a receipt or proof of purchase, and must be unworn and returned in
        original condition.</p>

    <p> Refunds are always performed using the method of payment. If you choose to return the garment in-store, please
        make sure you have your credit card that you made the online purchase with and that the card holder is present
        at the time of the return. This will enable the staff member to process the return/exchange for you.</p>

    <p> In-store return & exchange policies apply. All conditions above are in addition to your statutory rights.</p>
</div>

<div class="std">
    <h3>Accessories In-Store and Online Returns</h3>

    <p>As we are not able to determine wear on accessories, an exchange or refund can only granted in instances of
        damaged on arrival. If you receive an item that is DOA, please contact sales@peterjackson.com or
        info@peterjacksons.com as soon as possible.</p>
</div>

<div class="std">
    <h3>Returns from New Zealand</h3>

    <p>For returns from New Zealand, orders will need to be sent back to the Peter Jackson Head office in Melbourne Australia.</p>

    <p>New Zealand exchanges will be charged a re-shipping fee of AU$30.00 to have the new goods shipped back to you. We
        will send you an invoice prior to shipping the order.</p>

    <p>To send your order back to us, simply take the following steps:</p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Fill in the return form that
        came with your order and include it in the return parcel.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Bag or box your items with
        either packaging paper or a shipping bag</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>Address your parcel to: Peter
        Jackson Online Returns: 426 Johnston St Abbotsford: VIC: 3067</p>
</div>

