<article class="about-us">
    <section class="menu-about">
        <div class="about-block">
            <div class="about-block__image"><img src="{{view url='img/assets/banner-top-measure-app.jpg'}}"></div>
            <div class="about-block__text about-block__text--m2m">
                <img src="{{view url='img/assets/made-to-measure-logo.png'}}">
            </div>
        </div>
    </section>
    <section class="breadcrumbs">
        <ul class="breadcrumbs__items">
            <li class="breadcrumbs__item breadcrumbs__item--underline">
                <a href="{{store url='made-to-measure'}}">Made to Measure</a>
            </li>
            <li class="breadcrumbs__item">
                <strong class="breadcrumbs__item breadcrumbs__item--last"><span class="breadcrumbs__separator">&gt;</span> Custom Tailored Made Suit Appointments</strong>
            </li>
            <li class="breadcrumbs__item breadcrumbs__item--bold breadcrumbs__item--right" id="return-to-previous"><a href="{{store url='made-to-measure'}}">&lt; Return To Previous</a></li>
        </ul>
    </section>
    <section class="about-us-wrapper about-us-wrapper--990 ">
        <div class="measure-appointment__text-container">
            <h1 class="measure-appointment__title">SCHEDULE YOUR APPOINTMENT</h1>
            <p class="measure-appointment__text">Our Made to Measure experience is tailored around you, from the choice of fabric and fit to the where and when of your first appointment. Schedule an individual consultation with your personal Peter Jackson Made to Measure specialist below.</p>
        </div>

        <iframe src="https://app.acuityscheduling.com/schedule.php?owner=12422034" width="100%" height="800" frameBorder="0" class="measure-appointment__app"></iframe>
        <script src="https://d3gxy7nm8y4yjr.cloudfront.net/js/embed.js" type="text/javascript"></script>
</article>
