<article class="about-us fyf">
    <section class="menu-about menu-about--no-border">
        {{widget type="Magento\Cms\Block\Widget\Block" template="Light4website_Cms::menu.phtml" block_id="about-us-menu"}}
    </section>
    <section class="about-us-wrapper about-us-wrapper--grey">
        <h1 class="about-us-wrapper__title about-us-wrapper__title--opening">Find your fit</h1>
        <div class="about-us-wrapper__text-box about-us-wrapper__text-box--centered-small">
            <p>Divided into three unique profiles, our Milan, Tokyo, and London Blocks offer an eclectic range of styling options for the modern man. From slim-fit silhouettes to soft shoulder construction, get to know our suit styles with our comprehensive tailoring guide.
            </p>
        </div>
    </section>
    <section class="about-us-wrapper about-us-wrapper--grey">
        <ul class="fyf-nav">
            <li class="fyf-nav__item fyf-nav__item--active">Milan</li>
            <li class="fyf-nav__item">London</li>
            <li class="fyf-nav__item">Tokyo</li>
        </ul>
        <div class="fyf-slider">
            <div class="fyf-slider__slides init-slick">
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{media url="wysiwyg/about-us/suit-fit-guide-tokio.png"}}" alt="" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">Tokyo Fit</h1>
                        <p>Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The Tokyo features a lightly padded and narrow shoulder creating a more defined and structured look.</p>
                        <button class="fyf-slider__button">Explore Tokyo Suits</button>
                    </div>
                </div>
                </div>
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{media url="wysiwyg/about-us/tokio-suit.png"}}" alt="" /><img src="{{media url="wysiwyg/about-us/suit-fit-guide-tokio.png"}}" alt="" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">London Fit</h1>
                        <p>Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The Tokyo features a lightly padded and narrow shoulder creating a more defined and structured look.</p>
                        <button class="fyf-slider__button">Explore Tokyo Suits</button>
                    </div>
                </div>
                </div>
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{media url="wysiwyg/about-us/tokio-suit.png"}}" alt="" /><img src="{{media url="wysiwyg/about-us/suit-fit-guide-tokio.png"}}" alt="" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">Milan Fit</h1>
                        <p>Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The Tokyo features a lightly padded and narrow shoulder creating a more defined and structured look.</p>
                        <button class="fyf-slider__button">Explore Tokyo Suits</button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>
</article>
