<section class="new-wave-banner">
    <div class="new-wave-banner__top">
        <img src="{{view url='img/assets/the-new-wave/new-wave.png'}}">
    </div>
</section>

<section class="new-wave-content">
    <div class="new-wave-content__wrapper">
        <p>
            Celebrating the spirit of reinvention, The New Wave seeks to redefine modern tailoring, drawing inspiration
            from the countercultural movement of the 1980s to develop an adventurous new collection, steeped
            inexpressive colourways that challenge conventional suiting.
        </p>
        <p>
            The post-punk era represented a time of change, where new trends in music, art, design and technology
            created a bolder visual aesthetic. Taking influence from this, the SS17 range reflects the modernisation
            of tailoring, shifting towards tailored separates and street styled sartorialism.
        </p>
        <p>
            Modern silhouettes give rise to a more relaxed profile, with soft tailored construction creating a
            comfortable and breathable garment for active summer lifestyles. Complemented with lightweight linens
            and cool wool Merino suits, SS17 creates an agile range for versatile summer wardrobes.
        </p>

        <a href="#" class="new-wave-content__scroll-down"></a>
    </div>
</section>

<section class="new-wave-video">
    <div class="new-wave-video__wrapper">
        <iframe id="player" frameborder="0" allowfullscreen="1" title="YouTube video player" width="100%" height="100%" src="https://www.youtube.com/embed/tHY-XW1XZRk?&controls=0&loop=1&autoplay=1&showinfo=0"></iframe>
    </div>
</section>

<section class="new-wave-posters">
    <div class="new-wave-posters__box">
        <img src="https://www.peterjacksons.com/skin/frontend/peter_jackson_new/may2015/images/2017/ss17/ss17-art-01.jpg" class="new-wave-posters__img">

        <div class="new-wave-posters__right-side">
            <h1>
                Sunshine<br>
                <strong>staples</strong>
            </h1>
            <p>
                Redefine modern tailoring and make your<br>
                mark with our new collection of cool<br>
                wool and linen suits, perfect for summer<br>
                sojourns.
            </p>
            <button class="btn" onclick="location.href='/mens-suits-1.html'">Shop Suit</button>
        </div>
    </div>
</section>
