<div class="widget-normal-timeline widget-desktop widget-prepended-detail widget-wrapper">
    <div id="widget-timeline-detail" class="widget-timeline-detail widget-hidden" data-photo-id="">
        <div class="widget-detail-outer-container ">
            <div class="widget-detail-container" data-resource-url="">
                <div class="widget-detail-content">
                    <div class="widget-detail-left">
                        <div class="widget-image-container" style="position:relative;">
                            <img class="widget-detail-image" id="widget-instagram-image-url" src="">
                        </div>
                    </div>
                    <div class="widget-detail-right">
                        <a id="widget-detail-branding" style="display: block !important;"
                           href="https://store.magenest.com/" target="_blank"><span class="powered-by">Powered by</span>
                            MAGENEST</a>
                        <div class="widget-detail-nav-bar-arrows">
                            <div class="widget-detail-nav-button" id="widget-prev-post">
                                <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:svg="http://www.w3.org/2000/svg">
                                    <g>
                                        <path class="widget-arrow" fill="none" stroke-width="1px"
                                              d="m22.5,0l-15,15l15,15" id="widget-left-path" stroke="#222"></path>
                                    </g>
                                </svg>
                            </div>
                            <div class="widget-detail-nav-button" id="widget-next-post">
                                <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:svg="http://www.w3.org/2000/svg">
                                    <g>
                                        <path class="widget-arrow" stroke="#222" id="widget-left-path"
                                              d="m7.5,0l15,15l-15,15" fill="none"></path>
                                    </g>
                                </svg>
                            </div>
                            <div class="widget-detail-nav-bar-close">
                                <div class="widget-detail-nav-button" id="widget-detail-close">
                                    <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"
                                         xmlns:svg="http://www.w3.org/2000/svg">
                                        <g id="layer1" stroke="#222" class="widget-arrow" stroke-width="1px"
                                           fill="none">
                                            <path d="m0,0l30,30"></path>
                                            <path d="m30,0l-30,30"></path>
                                        </g>
                                    </svg>
                                </div>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div class="widget-products-title widget-single-product"></div>
                        <div class="featured-products" style="display: none;">
                            <span>FEATURED PRODUCTS</span>
                        </div>
                        <div class="widget-text-link-container"></div>
                        <div class="widget-divider"></div>
                        <div style="clear:both;"></div>
                        <div class="widget-detail-title"></div>
                        <div class="widget-post-info">
                            <a href="" target="_blank" id="widget-instagram-url">
                                <span class="widget-service-username">INSTAGRAM // </span><span
                                        class="widget-service-username" id="created_at_instagram"></span>
                            </a>
                        </div>
                        <div class="widget-detail-shares" style="display: none;">
                            <a class="widget-share widget-facebook-share" href="" target="_blank">
                                <i class="widget-icon widget-fa-facebook"></i>
                            </a>
                            <a class="widget-share widget-mail-share" href="" target="_blank">
                                <i class="widget-icon widget-fa-envelope_alt"></i>
                            </a>
                            <a class="widget-share widget-link-share widget-twitter-share" target="_blank" href="">
                                <i class="widget-icon widget-fa-twitter"></i>
                            </a>
                            <a class="widget-share widget-link-share widget-pinterest-share" href="" target="_blank"
                               data-pin-do="buttonPin"
                               data-pin-config="above">
                                <i class="widget-icon widget-fa-pinterest"></i>
                            </a>
                            <a class="widget-share widget-link-share widget-copied-link" href="" target="_blank">
                                <i class="widget-icon widget-fa-link"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="widget-buy-container widget-unslid"></div>
            </div>
        </div>
    </div>
</div>