<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">


    <div class="order-details__items--mobile">

            <div class="order-details-title">

                <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                    <div class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?>
                    </div>
                    <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addtInfoBlock) :?>
                        <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
                    <?php endif; ?>
                    <?php echo $block->escapeHtml($_item->getDescription()) ?>
                </td>

            </div>

            <div class="order-details__items--mobile-col">

                <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                    <div><span class="title"><?php /* @escapeNotVerified */ echo __('Price:'); ?></span><?php echo $block->getItemPriceHtml(); ?></div>
                </td>

                <td class="col size" data-th="<?php echo $block->escapeHtml(__('Size')); ?>">
                    <div>

                        <?php if ($_options = $block->getItemOptions()): ?>
                            <?php foreach ($_options as $_option) : ?>
                                <div>
                                    <?php echo $block->escapeHtml($_option['label']) ?>
                                    <?php if (!$block->getPrintStatus()): ?>
                                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                        <?php else: ?>
                                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <div>
                                            <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </td>

            </div>

            <div class="order-details__items--mobile-col">

                <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
                    <div><span class="title"><?php /* @escapeNotVerified */ echo __('SKU:'); ?></span>
                    <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></div>
                </td>

                <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
                    <ul class="items-qty">
                    <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                        <li class="item">
                            <span class="title"><?php /* @escapeNotVerified */ echo __('QTY:'); ?></span>
                            <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
                        </li>
                    <?php endif; ?>
                    </ul>
                </td>

            </div>

    </div>

    <div class="order-details__items--desktop">
        <div class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
            <div class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?>
                <?php if ($_options = $block->getItemOptions()): ?>
                    <?php foreach ($_options as $_option) : ?>
                        <div class="order-details__items--mobile-size">
                            <?php echo $block->escapeHtml($_option['label']) ?>
                            <?php if (!$block->getPrintStatus()): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            <?php else: ?>
                                <div>
                                    <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>



            <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addtInfoBlock) :?>
                <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </div>
        <div class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><div><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></div></div>
        <div class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <?php echo $block->getItemPriceHtml(); ?>
        </div>
        <div class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <ul class="items-qty">
                <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                    <li class="item">
                        <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered:'); ?></span>
                        <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <div class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
            <?php echo $block->getItemRowTotalHtml(); ?>
        </div>
    </div>


</tr>
