<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="breadcrumbs__items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="breadcrumbs__item <?php /* @escapeNotVerified */ echo $crumbName ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                    <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                </a>
                <span class="breadcrumbs__separator">></span>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong class="breadcrumbs__item breadcrumbs__item--last"><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
        <?php echo $block->getChildHtml('return.to.previous'); ?>
    </ul>

</div>
<?php endif; ?>
