<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */

if (trim($block->getPageHeading())) {
    $title = '<h1>' . $block->escapeHtml($block->getPageHeading()) . '</h1>';
}
?>
<?php if ($title): ?>
    <div class="category-description catalog-main__description">
        <div class="catalog-main__description--left-column">
            <a href="javascript:history.go(-1)" class="catalog-main__description--back"></a>
        </div>
        <div class="catalog-main__description--right-column">
            <h1 class="page-main__description--right-column"
                <?php /* @escapeNotVerified */ echo $title ?>
            </h1>
        </div>
    </div>
<?php endif; ?>






