<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
    <div class="page-main__title<?php /* @escapeNotVerified */ echo $cssClass; ?> page-main__description">
        <div class="page-main__description--left-column">
            <a href="javascript:history.go(-1)" class="page-main__description--back"></a>
        </div>
        <h1 class="page-main__description--right-column"
            <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
            <?php endif; ?>>
            <?php /* @escapeNotVerified */ echo $title ?>
        </h1>
        <?php echo $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
