<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php /* @escapeNotVerified */ echo $block->getChildHtml('respTopSearch'); ?>
<nav class="header-responsive__navigation">
    <ul>
        <li class="level0">
            <div>
                <a href="/storelocator">Stores</a>
            </div>
        </li>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php /* @escapeNotVerified */ echo $block->getChildHtml('catalogTopResp'); ?>
    </ul>
</nav>
