<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
$helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
if($helper->moduleEnabled() && $helper->isFakeMail()) : ?>
	<div class="pslogin-fake-email-message" data-mage-init='{"pslogin":{}}'>
		<div class="content">
			<div class="close-message">&#10005;</div>
			<p>
				<?php echo __('Your account needs to be updated. The email address in your profile is invalid. Please indicate your valid email address by going to the <a href="%1">Account edit page</a>', $block->getUrl('customer/account/edit')); ?>
			</p>
		</div>
	</div>
<?php endif; ?>