<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update Wishlist') ?>" class="action update">
        <span><?php /* @escapeNotVerified */ echo __('Update Wishlist') ?></span>
    </button>
<?php endif;?>
