<?php

// @codingStandardsIgnoreFile

/* @var $block \MagicToolbox\Magic360\Block\Adminhtml\Settings\Edit\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>
<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $element->getElementHtml() ?>
    <?php else: ?>
    <div<?php /* @escapeNotVerified */ echo $fieldAttributes ?>>
        <?php echo $element->getLabelHtml() ?>
        <div class="admin__field-control control">
            <?php echo $element->getElementHtml(); ?>
            <?php /* @escapeNotVerified */ echo $note ?>
        </div>
        <div class="field-status">
            <?php if ($element->getStatus() < 2): ?>
            <div class="magictoolbox-switcher" onselectstart='return false;'>
                <input type="checkbox" id="<?php echo $element->getId(); ?>-switcher" name="<?php echo str_replace('magictoolbox[', 'magictoolbox-switcher[', $element->getName()); ?>" class="magictoolbox-switcher-status"<?php echo $element->getStatus() ? ' checked="checked"' : ''; ?> />
                <label class="magictoolbox-switcher-label"
                       for="<?php echo $element->getId(); ?>-switcher"
                       data-text-on="<?php /* @escapeNotVerified */ echo __('Enabled'); ?>"
                       data-text-off="<?php /* @escapeNotVerified */ echo __('Disabled'); ?>"
                       title="<?php /* @escapeNotVerified */ echo $element->getStatus() ? __('Enabled') : __('Disabled'); ?>"></label>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>
