<?php
/**
 *
 */
?>
<div class="blog-sidebar wp-sidebar">
	<?php echo $this->getChildHtml() ?>
	<section class="blog-sidebar__subscribe">
		<h6 class="blog-sidebar__title blog-sidebar__title--subscribe">Stay up to date with the latest style tips</h6>
	</section>
	<section class="blog-sidebar__instagram">
		<h6 class="blog-sidebar__title">Instagram</h6>
	</section>
	<section class="blog-sidebar__facebook">
		<h6 class="blog-sidebar__title">Facebook</h6>
        <div class="fb-page" data-href="https://www.facebook.com/peterjacksonmenswear" data-tabs="timeline" data-width="270" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/peterjacksonmenswear" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/peterjacksonmenswear">Peter Jackson</a></blockquote></div>

	</section>
</div>
