<?php
/**
 *
 */
?>
<div class="blog-sidebar wp-sidebar">
	<?php echo $this->getChildHtml() ?>
	<section class="blog-sidebar__subscribe">
		<h6 class="blog-sidebar__title blog-sidebar__title--subscribe">Stay up to date with the latest style tips</h6>
	</section>
	<section class="blog-sidebar__instagram">
		<h6 class="blog-sidebar__title">Instagram</h6>
        <?php echo wdi_feed(array('id'=>'1')); ?>
	</section>
	<section class="blog-sidebar__facebook">
		<h6 class="blog-sidebar__title">Facebook</h6>
        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fpeterjacksonmenswear&tabs=timeline&width=270&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="270" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
	</section>
</div>
