<?php
/**
 *
 */
?>
<div class="blog-sidebar wp-sidebar">
	<?php echo $this->getChildHtml() ?>
	<section class="blog-sidebar__subscribe">
		<h6 class="blog-sidebar__title blog-sidebar__title--subscribe">Stay up to date with the latest style tips</h6>
        <div>
            <form action="https://pub.s7.exacttarget.com/ce14bqbgxxy" id="subscribe-form-blog" name="subscribeForm" method="post">
                <div class="newsletter">
                    <div class="newsletter__input-wrap"><input type="text" required class="newsletter__input" name="name" placeholder="First name"></div>
                    <div class="newsletter__input-wrap"><input type="email" required class="newsletter__input" name="email" placeholder="Email Address"></div>
                    <input type="hidden" name="Source" value="Blog" />
                    <div class="newsletter__button-wrap"><input type="submit" value="Subscribe" class="button newsletter__submit"></div>
                    <div class="newsletter__messages"></div>
                </div>
            </form>
        </div>
        <!-- End Salesforce Signup Form -->
	</section>
	<section class="blog-sidebar__instagram">
		<h6 class="blog-sidebar__title">Instagram </h6><span class="blog-sidebar__instalink">@PETERJACKSONAU</span>
        <script src="https://lightwidget.com/widgets/lightwidget.js"></script><iframe src="https://lightwidget.com/widgets/89f5be08b3155ec89d98ae02f6aec509.html" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>

    </section>
	<section class="blog-sidebar__facebook">
		<h6 class="blog-sidebar__title">Facebook</h6>
        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fpeterjacksonmenswear&tabs=timeline&width=270&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="270" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
	</section>
</div>
