<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$categoryId = $category->getId();
$promo_block_suits = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-suits')->toHtml();
$promo_block_shirts = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-shirts')->toHtml();
$promo_block_ties = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-ties')->toHtml();
?>

<?php if ($categoryId == 4): ?>
    <div class="catalog-item__promo catalog-item__promo--product">
        <?php echo $promo_block_suits; ?>
    </div>
<?php endif; ?>

<?php if ($categoryId == 5): ?>
    <div class="catalog-item__promo catalog-item__promo--product">
        <?php echo $promo_block_shirts; ?>
    </div>
<?php endif; ?>

<?php if ($categoryId == 74): ?>
    <div class="catalog-item__promo catalog-item__promo--product">
        <?php echo $promo_block_ties; ?>
    </div>
<?php endif; ?>

<div class="product-options-wrapper product-info-main__options-wrapper" id="product-options-wrapper"<?php /* @escapeNotVerified */ echo $required; ?>>
    <div class="fieldset product-info-main__fieldset" tabindex="0">
        <?php echo $block->getChildHtml('', true);?>
    </div>
    <?php if ($block->shouldRenderQuantity()): ?>
        <div class="product-info-main__qty-select control select__wrapper select__wrapper--qty">
            <figure class="select__wide-arrow"></figure>
            <select class="select__pdp-select" type="number" name="qty" id="qty"
                    title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                    data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                    required>
                <?php for($i = 1; $i < 11; $i++): ?>
                    <option value="<?php echo $i ?>"><?php echo $i ?></option>
                <?php endfor; ?>
            </select>
        </div>
    <?php endif; ?>
    <div class="product-info-main__size-chart">
        <?php /* @escapeNotVerified */ echo __('Size Guide'); ?>
    </div>
    <?php echo $block->getLayout()->createBlock('Light4website\CMSUpdate\Block\NonCacheableBlock')->setBlockId('size-chart')->toHtml();?>
</div>

<script>
    require(['jquery'],
        function ($) {
            $('.product-info-main__size-chart').click(function(){
                $('.size-chart-overlay').css('position', 'fixed');
            });

            $('.size-chart__close').click(function(){
                $('.size-chart-overlay').css('position', '');
            });
        });
</script>

