<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>


<div class="product-options-wrapper" id="product-options-wrapper"<?php /* @escapeNotVerified */ echo $required; ?>>
    <div class="fieldset" tabindex="0">
        <?php echo $block->getChildHtml('', true);?>
    </div>
    <?php if ($block->shouldRenderQuantity()): ?>
        <div class="control select__wrapper select__wrapper--product-page">
            <figure class="select__arrow"></figure>
            <select class="select__select" type="number" name="qty" id="qty"
                    title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                    data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                <?php for($i = 1; $i < 11; $i++): ?>
                    <option value="<?php echo $i ?>"><?php echo $i ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <article class="product-content__size-chart">
            <p><?php /* @escapeNotVerified */ echo __('View'); ?></br><?php /* @escapeNotVerified */ echo __('Size Chart') ?></p>
        </article>
    <?php endif; ?>
</div>

