<?php

/** @var $block Magento\Framework\View\Element\Template */
?>
<div class="floating-addtocart" data-mage-init='{"js/floatingAddtocart":{}}'>
    <div class="floating-addtocart__price-wrapper">
        <div class="floating-addtocart__price-text">
            Price
        </div>
        <div class="floating-addtocart__price">
            <?php echo $block->getChildHtml('floating.button.price'); ?>
        </div>
    </div>
    <div class="button floating-addtocart__button">
        <span>Add to Cart</span>
    </div>
</div>