<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$title = '';
$text = $block->escapeHtml($block->getPageHeading());
$alttext = substr($text, 0, strpos($text, "-"));
if (trim($block->getPageHeading())) {
    $title = '<span' .  $block->getAddBaseAttribute() . '>' . $alttext . '</span>';
}
?>
<div class="success-popup" id="success-popup">
    <div class="success-popup__overlay">
        <div class="success-popup__popup">
            <div class="success-popup__body">
                <div class="success-popup__image">
                    <img src="" class="success-popup__img" data-mage-init='{"js/success-popup": {}}' />
                </div>
                <div class="success-popup__text">
                    <h1 class="success-popup__title"><?php /* @escapeNotVerified */ echo $title ?></h1>
                    <span class="success-popup__text">Successfully added to your cart</span>
                </div>
            </div>
            <div class="success-popup__buttons">
<!--                <button class="success-popup__continue">Continue Shopping</button>-->
<!--                <button class="success-popup__gotocheckout">Checkout</button>-->

                <a class="success-popup__continue" href="#">Continue Shopping</a>
                <a class="success-popup__gotocheckout" href="<?php echo $block->getBaseUrl() . 'checkout/'; ?>">Checkout</a>

            </div>
        </div>
    </div>
</div>

