<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
$product = $block->getProduct();
$popupText = sprintf(__('Successfully added %s to your cart'), $product->getName());

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var Magento\Catalog\Block\Product\AbstractProduct $abstractProductBlock */
$abstractProductBlock = $objectManager->create('Magento\Catalog\Block\Product\AbstractProduct');
$imageType = 'cart_page_product_thumbnail';
$image = $abstractProductBlock->getImage($product, $imageType);
$imageUrl = $image->getImageUrl();

?>
<div class="success-popup" id="success-popup">
    <div class="success-popup__overlay">
        <div class="success-popup__popup">
            <div class="success-popup__body">
                <div class="success-popup__image">
<!--                    <img src="" class="success-popup__img" data-mage-init='{"js/success-popup": {}}' />-->
                    <img src="<?php echo $imageUrl; ?>" class="success-popup__img" />
                </div>
                <div class="success-popup__text">
                    <span class="success-popup__text"><?php echo $popupText ?></span>
                </div>
            </div>
            <div class="success-popup__buttons">
                <a class="success-popup__continue" href="#"><?php echo __('Continue Shopping') ?></a>
                <a class="success-popup__gotocheckout" href="<?php echo $block->getBaseUrl() . 'checkout/'; ?>"><?php echo __('Checkout') ?></a>
            </div>
        </div>
    </div>
</div>
