<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php if ($_invoice && $_order): ?>
    <table class="email-items" style="border: 0;" width="500">
        <thead style="display: table;width: 520px;margin: 0 auto;">
            <tr>
                <th class="item-info" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-subtotal" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Subtotal'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody style="display: table;width: 520px;margin: 0 auto;">
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
