<?php 

if ($block->getOrderComment()): ?>
    <section class="admin__page-section ordercomment">
        <div class="admin__page-section-title">
            <span class="title"><?php echo __('Order Comment') ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php echo nl2br($block->escapeHtml($block->getOrderComment()));?>
        </div>
    </section>
<?php endif; ?>
