<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/* @var $block \Amasty\Shopby\Block\Adminhtml\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>
<script>
require(['prototype']); // for legacy-build.min.js contains toggleValueElements()
</script>
<?php $block->checkFieldDisable() ?>
<style>
    .admin__scope-old label.addafter {
        display: block;
    }
</style>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $element->getElementHtml() ?>
    <?php else: ?>
        <div<?php /* @escapeNotVerified */ echo $fieldAttributes ?>>
            <?php if ($elementBeforeLabel): ?>
                <?php echo $element->getElementHtml() ?>
                <?php echo $element->getLabelHtml() ?>
                <?php /* @escapeNotVerified */ echo $note ?>
            <?php else: ?>
                <?php echo $element->getLabelHtml() ?>
                <div class="admin__field-control control">
                    <?php /* @escapeNotVerified */ echo($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml(); ?>
                    <?php /* @escapeNotVerified */ echo $note ?>
                </div>
            <?php endif; ?>

            <div class="field-service" value-scope="<?php /* @escapeNotVerified */ echo $block->getScopeLabel()?>">
                <?php if ($block->canDisplayUseDefault()): ?>
                    <label for="<?php echo $element->getHtmlId() ?>_default" class="choice use-default">
                        <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                            type="checkbox"
                            name="use_default[]"
                            class="use-default-control"
                            id="<?php echo $element->getHtmlId() ?>_default"
                            <?php if ($block->usedDefault()): ?> checked="checked"<?php endif; ?>
                            onclick="toggleValueElements(this, this.parentNode.parentNode.parentNode)"
                            value="<?php echo $element->getName()?>"/>
                        <span class="use-default-label"><?php /* @escapeNotVerified */ echo __('Use Default Value') ?></span>
                    </label>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>