INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'ACT', 'Australian Capital Territory');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'NSW', 'New South Wales');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'VIC', 'Victoria');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'QLD', 'Queensland');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'SA', 'South Australia');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'WA', 'Western Australia');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'TAS', 'Tasmania');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('AU', 'NT', 'Northern Territory');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'AUK', 'Auckland');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'BOP', 'Bay of Plenty');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'CAN', 'Canterbury');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'GIS', 'Gisborne');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'HKB', 'Hawke''s Bay');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'MBH', 'Marlborough');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'MWT', 'Manawatu-Wanganui');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'NSN', 'Nelson');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'NTL', 'Northland');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'OTA', 'Otago');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'STL', 'Southland');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'TAS', 'Tasman');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'TRC', 'Taranaki');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'WKO', 'Waikato');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'WGN', 'Wellington');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'WTC', 'West Coast');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('NZ', 'CIT', 'Chatham Islands Territory');