<article class="about-us">
    <section class="menu-about">
        {{widget type="Magento\Cms\Block\Widget\Block" template="Light4website_Cms::menu.phtml" block_id="about-us-menu"}}
    </section>
    <section class="about-us-wrapper about-us-wrapper--990">
        <h1 class="about-us-wrapper__title about-us-wrapper__title--opening">About Us</h1>
        <div class="about-us-wrapper__text-box about-us-wrapper__text-box--centered about-us-wrapper__text-box--770">
            <p>Peter Jackson is an Australian garment maker constructing quality menswear with a passion for innovative design and a strong emphasis on revolutionising the menswear retail space. We recognise there’s a huge disparity between ‘disposable fashion’ and luxury garments in both quality and price; we stand to bridge that gap because we believe that fashion and luxury should be accessible to everyone.</p>
            <p>By challenging modern day fashion conventions and pushing boundaries, we believe the modern man deserves clothing constructed from the world’s best textiles without paying over the odds. Our brand is not only a testament to authentic craftsmanship but also represents our dedication to instilling confidence in men to embrace their fashion aspirations whilst making confident and lasting impressions.</p>
        </div>
    </section>
    <section class="about-us-wrapper about-us-wrapper--no-padding">
        <img class="about-us-wrapper__fullwidth-image" src="{{view url='img/assets/brand/about-us-banner.png}}">
    </section>
    <section class="about-us-wrapper about-us-wrapper--1550 about-us-wrapper--where-it-all-began">
        <div class="about-us-wrapper__text-box">
            <div class="about-us-wrapper__wiab-box about-us-wrapper__wiab-box--left"><img src="{{view url='img/assets/brand/about-us-peter.jpg}}" /></div>
            <div class="about-us-wrapper__wiab-box about-us-wrapper__wiab-box--right">
                <h1 class="about-us-wrapper__title">Where it all began</h1>
                <p>For over 7 decades we’ve believed in elevating the dress standards of all Australian men.</p>
                <p>Empowering them to draw confidence from their appearance, knowing that they will look their best and be ready for every occasion.</p>
                <p>This strong sense of purpose started in 1948, in the heart of Melbourne’s CBD-Little Bourke Street, where siblings Olga, Peter and David Jackson ran their iconic barbershop.</p>
                <p>Selling neckties, the trio’s foray into fashion gradually evolved into a full tailored Men’s range. Soon after, we promptly established ourselves as the number one destination for men’s fashion throughout Melbourne.</p>
                <p>With a new generation of Jacksons at the helm and more than 60 stores nationally, Peter Jackson still remains a family business echoing views and values established 70 years ago.</p>
            </div>
    </section>
</article>
