<section class="corporate-slider">
    <div class="corporate-slider__slide corporate-slider__slide--1">
        <img src="{{view url='img/assets/corporate/corporate4.jpg'}}"/>
    </div>

    <div class="corporate-slider__slide corporate-slider__slide--2">
        <img src="{{view url='img/assets/corporate/corporate1.jpg'}}"/>
    </div>

    <div class="corporate-slider__slide corporate-slider__slide--3">
        <img src="{{view url='img/assets/corporate/corporate2.jpg'}}"/>
    </div>

    <div class="corporate-slider__slide corporate-slider__slide--4">
        <img src="{{view url='img/assets/corporate/corporate3.jpg'}}"/>
    </div>
</section>

<section class="corporate-content">
    <div class="corporate-content__description">
        <h1>Corporate Styling</h1>

        <p>Peter Jackson offers corporate packages for some of Australia's leading organizations. </p>

        <p>Through our corporate service, we cater to all commercial sectors, offering businesses packages far greater
            than any uniform, while always receiving our highest level of service and ongoing support from our National
            Sales Manager.
        </p>

        <p>Our wide portfolio of partnerships and clients ranges from finance, real estate and hospitality, to diverse
            leading media giants and sports teams. With a 100% customizable selection of European textiles, we can
            tailor solutions depending on your size, requirements or your specific needs.
        </p>

        <p>
            With us, you won't be wearing just an excellent garment, but also the tradition, history, reputation and
            style that characterises our brand as one of Australia's leading premium menswear brands.
        </p>
    </div>

    <div>
        <form>
            <input class="corporate-content__input" type="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,63}$" name="contact_us[email]" placeholder="Email*" title="Your email address" required>
            <input class="corporate-content__input" type="text" pattern="([A-z0-9À-ž\s]){2,}" name="contact-us[name]" placeholder="Your full name*" title="Only alphanumeric characters allowed" required>
            <input class="corporate-content__input" type="text" name="contact_us[subject]" placeholder="Subject*" title="Subject" required>
            <textarea class="corporate-content__textarea" name="contact_us[message]" placeholder="Type your enquiry here." title="Message" required></textarea>
            <button class="corporate-content__button" type="submit" title="Submit">Submit your enquiry</button>
        </form>
    </div>
</section>

<script>
    require(["js/corporate"], function(mod) {
        var corporateInit = new mod.corporate();
    })
</script>