<section class="main-banner">
    <div class="main-banner__wrapper">
        <div class="main-banner__inner">
            <div class="main-banner__content-box">
                <a href="https://www.peterjacksons.com/sale.html"><img class="main-banner__image" src="{{view url='img/assets/home-08-2018/Website_homepage_update_august_2018_the_PJ_Sale.png'}}"/></a>
                <div class="main-banner__header">
                    <p>With new styles added, the time is either now or</p>
                    <p>never to capitalize on our PJ Sale</p>
                </div>
                <button class="btn btn--padding" onclick="location.href='/mens-suits-1.html'">Shop Suits</button>
            </div>
        </div>
    </div>
</section>

{{block class="PandaGroup\CategoryWidget\Block\Category\Widget" template="PandaGroup_CategoryWidget::categorywidget.phtml"}}

<section class="home-banner home-banner__image home-banner__image--elevate home-banner__image--no-margin" onclick="location.href='/clothing/mens-blazers.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero">
                    <p class="elevate">Natural</p>
                    <p class="your-style">Selection</p>
                </div>
                <div class="home-banner__header--mobile">
                    <p>Coat Of</p>
                    <p>Arms</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">The last remaining days of our End of Season</p>
                    <p class="home-banner__text">Sale. With pure cool wool Jackets now from</p>
                    <p class="home-banner__text">$159</p>
                    <p class="home-banner__text-box--mobile home-banner__text-box--tactile">The last remaining days of our End of Season Sale. With pure cool wool Jackets now from $159</p>
                </div>
                <button class="btn" onclick="location.href='/clothing/mens-blazers.html'">Shop Jackets & Coats</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--shoe" onclick="location.href='/clothing/mens-shoes.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero home-banner__header--black">
                    <p class="elevate">Carving the</p>
                    <p class="your-style">path</p>
                </div>
                <div class="home-banner__header--mobile-black">
                    <p>Carving the</p>
                    <p>path</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text home-banner--black">A new collection of 100% Premium Italian leather</p>
                    <p class="home-banner__text home-banner--black">Boots & Shoes for those who lead the way.</p>
                    <p class="home-banner__text-box--mobile home-banner--black">A new collection of 100% Premium Italian leather Boots & Shoes for those who lead the way.</p>
                </div>
                <button class="btn btn-black" onclick="location.href='/about-us'">Shop Shoes</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--measure" onclick="location.href='/made-to-measure'">
    <button class="btn btn-measure" onclick="location.href='/made-to-measure'">Reserve Your Experience</button>
</section>

<script>
    require(["js/home"], function (home) {
        var homeInit = home();
    });
</script>