<section class="main-banner">
    <a href="/mens-suits-1.html">
        <img class="main-banner__image" src="{{view url='img/assets/home-08-2018/website_homepage_update_summer_2018_dedicated.png'}}"/>
    </a>
    <div class="main-banner__wrapper">
        <div class="main-banner__inner">
        </div>
    </div>
</section>

{{block class="PandaGroup\CategoryWidget\Block\Category\Widget" template="PandaGroup_CategoryWidget::categorywidget.phtml"}}

<section class="home-banner home-banner__image home-banner__image--elevate home-banner__image--no-margin" onclick="location.href='/shop-by-look/'">
    <video autoplay muted loop id="myVideo" poster="{{view url='img/assets/home-08-2018/MSFW18.jpg'}}">
        <source src="{{view url='videos/MSFW18.mp4'}}" type="video/mp4">
    </video>
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero">
                    <img class="home-banner__inner-image" src="{{view url='img/assets/home-08-2018/melbourne_fashion_week.png'}}">
                </div>
                <div class="home-banner__header--mobile">
                    <img class="home-banner__inner-image" src="{{view url='img/assets/home-08-2018/melbourne_fashion_week.png'}}">
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Melbourne Spring Fashion Week is in full</p>
                    <p class="home-banner__text">swing. Shop our runway now.</p>
                    <p class="home-banner__text-box--mobile home-banner__text-box--tactile">Melbourne Spring Fashion Week is in full swing. Shop our runway now.</p>
                </div>
                <button class="btn" onclick="location.href='/shop-by-look/'">Shop Runway</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--support home-banner__image--no-margin" onclick="location.href='/mens-accessories/mens-bags.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero">
                    <p class="elevate libre-italic">Sartorial</p>
                    <p class="your-style libre-bold">Support</p>
                </div>
                <div class="home-banner__header--mobile">
                    <p class="libre-italic">Sartorial</p>
                    <p class="libre-bold">Support</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Get carried away with our SS18 collection</p>
                    <p class="home-banner__text">of fine leather accessories.</p>
                    <p class="home-banner__text-box--mobile home-banner__text-box--tactile">Get carried away with our SS18 collection of fine leather accessories.</p>
                </div>
                <button class="btn" onclick="location.href='/mens-accessories/mens-bags.html'">Bags & Accessiories</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--shoe" onclick="location.href='/mens-shoes.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero home-banner__header--black">
                    <p class="elevate libre-bold">Summer <span class="libre-italic">steps</span></p>
                </div>
                <div class="home-banner__header--mobile home-banner__header--mobile-black">
                    <p class="elevate libre-bold">Summer</p>
                    <p class="libre-italic">steps</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text home-banner--black">A new collection of 100% Premium Italian leather</p>
                    <p class="home-banner__text home-banner--black">footwear is bound to make the right impression.</p>
                    <p class="home-banner__text-box--mobile home-banner--black">A new collection of 100% Premium Italian leather footwear is bound to make the right impression.</p>
                </div>
                <button class="btn btn-black" onclick="location.href='/mens-shoes.html'">Shop Shoes</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--measure" onclick="location.href='/made-to-measure'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero home-banner__header--black">
                    <p class="elevate libre-bold">Design your <span class="libre-italic">own</span> suit</p>
                </div>
                <div class="home-banner__header--mobile home-banner__header--mobile-black">
                    <p class="libre-bold">Design your <span class="libre-italic">own</span> suit</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Redefine modern tailoring and create a</p>
                    <p class="home-banner__text">suit, unique to your sense of style.</p>
                    <p class="home-banner__text-box--mobile">Redefine modern tailoring and create a suit, unique to your sense of style.</p>
                </div>
                <img class="home-banner__inner-image" src="{{view url='img/assets/home-08-2018/image_made_to_measure.png'}}"/>
                <div>
                    <button class="btn btn-measure" onclick="location.href='/made-to-measure'">Reserve Your Experience</button>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    require(["js/home"], function (home) {
        var homeInit = home();
    });
</script>