<section class="main-banner">
    <img class="main-banner__loader" id="home-loader" src="{{view url='img/assets/PJ_loader.gif"}} alt="" />
    <img class="main-banner__img" id="main-banner" src="{{view url='img/assets/home 25-09-18/main-banner-ann.png"}} alt="" style="display: none" />
    <div class="main-banner__wrapper">
        <a href="/mens-suits-1.html">
            <img class="main-banner__sign" src="{{view url='img/assets/home 25-09-18/70th anniversary 50off.png'}}" style="display: none"/>
        </a>
    </div>
</section>

{{block class="PandaGroup\CategoryWidget\Block\Category\Widget" template="PandaGroup_CategoryWidget::categorywidget.phtml"}}

<section class="home-banner home-banner__image home-banner__image--tailored-tropics home-banner__image--no-margin" onclick="location.href='/clothing/mens-blazers.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero">
                    <p class="elevate libre-italic">Tailored</p>
                    <p class="your-style libre-bold">Tropics</p>
                </div>
                <div class="home-banner__header--mobile">
                    <p class="libre-italic">Tailored</p>
                    <p class="libre-bold">Tropics</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Energetic and vibrant</p>
                    <p class="home-banner__text">nature-inspired tones in this</p>
                    <p class="home-banner__text">season’s Sports Jackets</p>
                    <p class="home-banner__text-box--mobile home-banner__text-box--tactile">Energetic and vibrant nature-inspired tones in this season’s Sports Jackets.</p>
                </div>
                <button class="btn" onclick="location.href='/clothing/mens-blazers.html'">Shop Sports Jackets</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--shoe" onclick="location.href='/mens-shoes.html'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero home-banner__header--black">
                    <p class="elevate libre-bold">Summer <span class="libre-italic">steps</span></p>
                </div>
                <div class="home-banner__header--mobile home-banner__header--mobile-black">
                    <p class="elevate libre-bold">Summer</p>
                    <p class="libre-italic">steps</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text home-banner--black">A new collection of 100% Premium Italian leather</p>
                    <p class="home-banner__text home-banner--black">footwear is bound to make the right impression.</p>
                    <p class="home-banner__text-box--mobile home-banner--black">A new collection of 100% Premium Italian leather footwear is bound to make the right impression.</p>
                </div>
                <button class="btn btn-black" onclick="location.href='/mens-shoes.html'">Shop Shoes</button>
            </div>
        </div>
    </div>
</section>

<section class="home-banner home-banner__image home-banner__image--measure" onclick="location.href='/made-to-measure'">
    <div class="home-banner__wrapper">
        <div class="home-banner__inner">
            <div class="home-banner__content-box home-banner__content-box--centered">
                <div class="home-banner__header home-banner__header--none home-banner__header--margin-zero home-banner__header--black">
                    <p class="elevate libre-bold">Design your <span class="libre-italic">own</span> suit</p>
                </div>
                <div class="home-banner__header--mobile home-banner__header--mobile-black">
                    <p class="libre-bold">Design your <span class="libre-italic">own</span> suit</p>
                </div>
                <div class="home-banner__header--none"></div>
                <div class="home-banner__text-box">
                    <p class="home-banner__text">Redefine modern tailoring and create a</p>
                    <p class="home-banner__text">suit, unique to your sense of style.</p>
                    <p class="home-banner__text-box--mobile">Redefine modern tailoring and create a suit, unique to your sense of style.</p>
                </div>
                <img class="home-banner__inner-image" src="{{view url='img/assets/home-08-2018/image_made_to_measure.png'}}"/>
                <div>
                    <button class="btn btn-measure" onclick="location.href='/made-to-measure'">Reserve Your Experience</button>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    require(["js/home"], function (home) {
        var homeInit = home();
    });
</script>