<div class="std">

    <h3>Conditions of Purchase</h3>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     A valid proof of purchase is required (bank statement or store receipt) on all return transactions.
    </p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     Under the Australian Consumer Law (ACL), consumers have a right to return faulty goods in certain circumstances.
    </p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     If the product has a major failure, the consumer has the right to choose between a replacement or refund. If the product has a minor failure, the business can choose to give the consumer a free repair instead of a replacement or refund.
    </p>

    <h3><i>What is a major failure?</i></h3>

    <p>A product or good has a major failure when:</p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     It has a problem that would have stopped someone from buying it if they’d known about it</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     It is unsafe</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     It is significantly different from any sample or description, or</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     It doesn’t do what the business said it would, or what the consumer asked for, and can’t easily be made suitable for such a purpose.</p>

    <br>

    <p>Businesses are not required by law to provide refunds to consumers simply because a consumer changed their mind about a purchase when there is no major or minor failure in relation to the good and the good was properly described.
    </p>
    <p>
        <i>This change of mind policy does not affect your rights under the Australian Consumer Law. If you purchased a product with a major fault, you have the right to ask for your choice of a replacement or refund. If you purchased a product with a minor fault, we can choose to give you a free repair instead of a replacement or refund.</i>
    </p>

    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     Peter Jackson is happy to offer a store credit for customers who have changed their mind. This is available up to 7 days after the purchases and the goods must be in original unworn condition.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     In store and online prices may vary depending upon the level of services provided.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     Gift cards can be redeemed for merchandise only at Peter Jackson stores. Gift cards cannot be redeemed for cash.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     Gift cards are valid for 12 months from the purchase date.</p>
    <p>•<span class="Apple-tab-span" style="white-space:pre" _mce_style="white-space: pre;">	</span>     Credit cards - All major credit cards are accepted. Credit cards will incur a 1% transaction fee.</p>

</div>

<div class="std">

    <h3>When can a consumer return faulty goods?</h3>

    <p>Under the ACL, consumers can return faulty goods within a reasonable time. The term “reasonable time” is not defined by the ACL. The nature of our goods a reasonable amount of time is 12 months for any assessment. Goods returned outside this duration cannot be accessed purely based on the time passed.</p>

</div>