<section class="sartorial-ninja-banner">
    <img src="{{view url='img/assets/sartorial-ninja/nathan-top-01.jpg'}}">
</section>

<section class="sartorial-ninja-content">
    <div class="sartorial-ninja-content__header">
        <h1 class="sartorial-ninja-content__title">Sartorial Ninja</h1>
        <h2 class="sartorial-ninja-content__description">
            Former Ninja Warrior and fashion aficionado; Nathan McCallum
            sits down with the PJ team to talk health, fitness and the Sydney fashion scene.
        </h2>
        <p class="sartorial-ninja-content__subtext">
            Emerging from the shadows in 2011 with the creation of the Bangarang Blog, fashion blogger and
            former participant in the ruthless Ninja Warrior series, Nathan McCallum’s unique blend of fashion
            and fitness commentary has struck a chord with the Australian public, now resonating with
            some 300,000 people online. Dedicated to building an authentic connection, McCallum humbly attributes
            his success to the rejection of trend based fashion, and creating a functional, down to earth aesthetic
            that draws on his interpretation of fashion centric styles, stripped back for every day living.
        </p>
    </div>

    <div class="sartorial-ninja-content__photos">
        <a href="#" class="sartorial-ninja-content__photos--half">
            <img src="{{view url='img/assets/sartorial-ninja/nathan-mid-01.jpg'}}">
        </a>
        <a href="#" class="sartorial-ninja-content__photos--half">
            <img src="{{view url='img/assets/sartorial-ninja/nathan-mid-02.jpg'}}">
        </a>
    </div>

    <div class="sartorial-ninja-content__quote">
        <p>
            “I take inspiration from friends when it comes to fashion. I am, also inspired by Nick Wooster,
            I love seeing the way he does his own thing.”
        </p>
    </div>

    <div class="sartorial-ninja-content__questions">
        <div class="sartorial-ninja-content__questions--left-box">
            <p>
                <strong>PJ: What age did you start getting into fashion?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                I started out in fashion when I was 15, helping out with the Visual Merchandising at the surf shop
                I worked in, then the passion just grew from there.
            </p>

            <p>
                <strong>PJ: You have an active interest in fashion, who do you look at for inspiration?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                I actually look to my friends for a lot of inspiration. Guys like Marcel Floruss, Adam Gallagher,
                Justin Livingston and Denny Balmaceda. They are all peers that are doing a great job in the world of
                menswear. Also, I have always been inspired by Nick Wooster, I love seeing the way he just does his
                own thing regardless of the trends.
            </p>

            <p>
                <strong>PJ: You have a great Instagram following, how did this take off?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                It's been a slow process, to be honest. I was lucky enough to have my blog up and running before
                the social media trend really grew, so I already had my foot in the door. I think just staying true to
                myself and posting exactly what I like has been crucial to people following along, and growing with me.
            </p>

            <p>
                <strong>PJ: What do you think is most fascinating about the Instagram community?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                I think just that: the sense of community really. I have so many legitimate friends that I have met
                through Instagram from all over the world. That's an incredible thing.
            </p>

        </div>
        <div class="sartorial-ninja-content__questions--photo">
            <img src="{{view url='img/assets/sartorial-ninja/nathan-mid-03.jpg'}}">
        </div>
    </div>

    <div class="sartorial-ninja-content__quote">
        <p>
            “My whole thing is about wanting to improve on myself everyday - health and fitness is a super easy way
            to stay on stop of that”
        </p>
    </div>

    <div class="sartorial-ninja-content__questions sartorial-ninja-content--left-side">
        <div class="sartorial-ninja-content__questions--right-box">
            <p>
                <strong>
                    PJ: Your overall lifestyle looks to be centred around health and fitness, what
                    motivates you here?
                </strong>
            </p>
            <p>
                <strong>NC:</strong>
                I guess my whole thing has always been about wanting to improve on myself every day. Health and
                fitness is a super easy way to stay on top of that.
            </p>

            <p>
                <strong>PJ: Who or what inspired you to get into health and fitness?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                My parents have always encouraged me to be healthy and active since I was a kid, I don't think there
                is a sport that I haven't played at one point or another. I joined a gym 4 years ago and have enjoyed
                challenging myself there ever since.
            </p>

            <p>
                <strong>PJ: How would you describe the current fashion scene in Sydney?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                The Sydney fashion scene is a tough one, particularly when it comes to menswear. We don't really have
                many brands stepping up to the plate as there are on a global scale. So it's great seeing brands like
                PJ continuing to reinvent themselves, and stay relevant as trends change.
            </p>

            <p>
                <strong>PJ: How would you describe your go to look?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                My go to look is pretty simple, but definitely my own. I love denim and basics, but I like to play
                with different styles and texture.
            </p>
            <p>
                <strong>PJ: Your style is unique, where do you draw your inspiration from?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                The whole reason I started Bangarang blog was to source inspiration for myself. I love scouring the web
                for unique looks and ideas and then interpreting them in my own way.
            </p>
            <p>
                <strong>PJ: What trends are you loving at the moment?</strong>
            </p>
            <p>
                <strong>NC:</strong>
                I love pink. It's great seeing the hints of soft pinks coming through in men's fashion currently.
            </p>

        </div>
        <div class="sartorial-ninja-content__questions--photo">
            <img src="{{view url='img/assets/sartorial-ninja/nathan-mid-04.jpg'}}">
        </div>
    </div>
</section>