<article class="about-us fyf">
    <section class="menu-about menu-about--no-border">
        {{widget type="Magento\Cms\Block\Widget\Block" template="Light4website_Cms::menu.phtml" block_id="about-us-menu"}}
    </section>
    <section class="about-us-wrapper about-us-wrapper--grey">
        <h1 class="about-us-wrapper__title about-us-wrapper__title--opening">Find your fit</h1>
        <div class="about-us-wrapper__text-box about-us-wrapper__text-box--centered about-us-wrapper__text-box--640">
            <p class="about-us-wrapper__thin-text">Divided into three unique profiles, our Milan, Tokyo, and London Blocks offer an eclectic range of styling options for the modern man. From slim-fit silhouettes to soft shoulder construction, get to know our suit styles with our comprehensive tailoring guide.
            </p>
        </div>
    </section>
    <section class="about-us-wrapper about-us-wrapper--grey">
        <ul class="fyf-nav">
            <li class="fyf-nav__item fyf-nav__item--active">Milan</li>
            <li class="fyf-nav__item">London</li>
            <li class="fyf-nav__item">Tokyo</li>
        </ul>
        <div class="fyf-slider">
            <div class="fyf-slider__slides init-slick">
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{view url='img/assets/brand/WT17_R08_LOOK.png'}}" alt="Milan Fit" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">Milan Fit</h1>
                        <p>Inspired by the latest trends in Italy, France and Spain, our Milan Block utilises soft shoulder construction with minor roping for an unmistakably European profile. The slimmer fit and modern cut make this suit’s style perfect for on and off-the-clock sojourns.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The Milan utilises a soft shoulder construction method with minor roping for a refined, but casual look.</p>
                        <button class="fyf-slider__button" onclick="location.href='/mens-suits-1/milan.html'">Explore Milan Suits</button>
                    </div>
                </div>
                </div>
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{view url='img/assets/brand/WT17_R06_LOOK.png'}}" alt="London Fit" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">London Fit</h1>
                        <p>A contemporary spin on traditional tailoring, the London Block offers our most versatile fit for all physiques. Falling gently from the shoulder, the fabric naturally conforms to your bodies silhouette, creating a clean, comfortable and sophisticated fit.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The London features a lightly padded shoulder creating a greater definition for a more refined corporate look.</p>
                        <button class="fyf-slider__button" onclick="location.href='/mens-suits-1/london.html'">Explore London Suits</button>
                    </div>
                </div>
                </div>
                <div>
                <div class="fyf-slider__slide">
                    <div class="fyf-slider__img">
                        <img src="{{view url='img/assets/brand/WT17_R05_LOOK.png'}}" alt="" />
                    </div>
                    <div class="fyf-slider__content">
                        <h1 class="fyf-slider__title">Tokyo Fit</h1>
                        <p>Streamlined sophistication, the Tokyo Block boasts our collections most fitted suit style, constructed with tapering in the waist, sleeve and trouser leg. Balanced with a shorter rise, the slimmer silhouette gives rise to a more modern aesthetic, perfect for the fashion faithful.</p>
                        <h2 class="fyf-slider__title-h2">Shoulder construction</h2>
                        <p>The Tokyo features a lightly padded and narrow shoulder creating a more defined and structured look.</p>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>
</article>

<script>
    require(["js/suitFitGuide"], function(suitFitGuide) {
        var suitFitInit = suitFitGuide();
    })
</script>
