<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php
$_helper = $this->helper('WeltPixel\LazyLoading\Helper\Data');
$isRequestAjax = $_helper->isRequestAjax();
$imgSrc = $_helper->getImageLoader();
$imgDataOriginal = $block->getImageUrl();
if ($isRequestAjax) {
    $imgSrc = $imgDataOriginal;
}
?>

<span class="product-image-container"
      style="width:<?php /* @escapeNotVerified */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo ($block->getRatio() * 100); ?>%;">
        <img class="product-image-photo lazy"
             <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             src="<?php /* @escapeNotVerified */ echo $imgSrc; ?>"
             data-original="<?php /* @escapeNotVerified */ echo $imgDataOriginal; ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/></span>
</span>
