<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">

    <div class="select__wrapper">
        <figure class="select__arrow"></figure>
        <select id="sorter" data-role="sorter" class="sorter-options select__select">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>

                <?php // Show 'Sort by' placeholder on select and disable sort by 'Position' ?>
                <option <?php if ('position' === $block->getCurrentOrder()) echo 'selected'; ?> hidden>Sort by</option>
                <?php if ($_key === 'position') continue; ?>

                <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
