<?php

// @codingStandardsIgnoreFile

/** @var $block \MagicToolbox\Magic360\Block\Adminhtml\Product\Edit\Magic360\SpinOptions */

$formName = $block->getFormName();
$multiRows = $block->getOptionValue('multi_rows');
$columns = $block->getOptionValue('columns');
$rows = $block->getOptionValue('rows');
?>
<div class="admin__field">
    <label class="admin__field-label" for="magic360_multi_rows">
        <span><?php echo __('Multi-row spin') ?></span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox"
                   name="magic360[multi_rows]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<?php echo $multiRows ?>"
                   class="admin__actions-switch-checkbox"
                   id="magic360_multi_rows"
                   <?php if ($multiRows) { ?> checked="checked"<?php } ?>>
            <label class="admin__actions-switch-label" for="magic360_multi_rows">
                <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<div class="admin__field admin__field-small<?php if (!$multiRows) { ?> _disabled<?php } ?>">
    <label class="admin__field-label" for="magic360_columns">
        <span><?php echo __('Number of images on X-axis') ?></span>
    </label>
    <div class="admin__field-control">
        <input type="text"
               name="magic360[columns]"
               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
               value="<?php echo $columns ?>"
               class="admin__control-text"
               id="magic360_columns"
               <?php if (!$multiRows) { ?> disabled="disabled"<?php } ?>>
    </div>
</div>
<div class="admin__field admin__field-small<?php if (!$multiRows) { ?> _disabled<?php } ?>">
    <label class="admin__field-label" for="magic360_rows">
        <span><?php echo __('Number of images on Y-axis') ?></span>
    </label>
    <div class="admin__field-control">
        <input type="text"
               name="magic360[rows]"
               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
               value="<?php echo $rows ?>"
               class="admin__control-text"
               id="magic360_rows"
               <?php if (!$multiRows) { ?> disabled="disabled"<?php } ?>>
    </div>
</div>
<script>
    require([
        'jquery',
    ], function ($) {
        $('#magic360_multi_rows').bind('change', function() {
            var disabled = $(this).attr('checked') ? false : true;
            $('#magic360_columns').attr('disabled', disabled);
            $('#magic360_rows').attr('disabled', disabled);
            if (disabled) {
                $('#magic360_columns').parent().parent().addClass('_disabled');
                $('#magic360_rows').parent().parent().addClass('_disabled');
            } else {
                $('#magic360_columns').parent().parent().removeClass('_disabled');
                $('#magic360_rows').parent().parent().removeClass('_disabled');
            }
        });
    });
</script>
