<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
try {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    /** @var \Magento\Checkout\Model\Session $checkoutSession */
    $checkoutSession = $objectManager->create('Magento\Checkout\Model\Session');
    $virtualCheckout = $checkoutSession->getQuote()->isVirtual();
} catch (\Exception $e) {
    $virtualCheckout = false;
}
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="breadcrumbs__items">
        <?php $stepCounter = 1; ?>
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>

            <?php if ($virtualCheckout === true AND $crumbName === 'delivery') continue; ?>

            <li class="breadcrumbs__item breadcrumbs__item--<?php /* @escapeNotVerified */ echo $crumbName ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                    <?php echo $stepCounter.'. '.$block->escapeHtml($crumbInfo['label']) ?>
                </a>
                <span class="breadcrumbs__separator"> > </span>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong class="breadcrumbs__item breadcrumbs__item--last"><?php echo $stepCounter.'. '.$block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $stepCounter.'. '.$block->escapeHtml($crumbInfo['label']) ?>
                <span class="breadcrumbs__separator"> > </span>
            <?php endif; ?>
            </li>
        <?php $stepCounter++; ?>
        <?php endforeach; ?>
        <?php echo $block->getChildHtml('return.to.previous'); ?>
    </ul>

</div>
<?php endif; ?>
