<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="border: 0;" width="500">
        <thead style="display: table;width: 520px;margin: 0 auto;">
            <tr>
                <th class="item-info" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-price" style="background-color: transparent;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                    <?= /* @escapeNotVerified */  __('Price'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody style="display: table;width: 520px;margin: 0 auto;">
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>

        <tbody>
            <table border="0" cellpadding="0" cellspacing="0" width="520" id="templateColumns" style="margin: 0 auto;border-bottom: 1px solid #000000">
                <tr>
                    <td align="center" valign="top" width="50%" class="templateColumnContainer">
                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                            <tr>
                                <td valign="top" class="leftColumnContent" style="font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:200;color: #000000;padding: 10px 10px 20px 10px;">
                                    Payment method
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td align="center" valign="top" width="50%" class="templateColumnContainer">
                        <table border="0" cellpadding="10" cellspacing="0" width="100%">
                            <tr>
                                <td valign="top" class="rightColumnContent" style="text-align: right;font-size: 15px;font-family: sofia-pro,sans-serif;font-style:normal;font-weight:400;color: #000000;">
                                    <?php echo $_order->getPayment()->getMethodInstance()->getTitle() ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </tbody>

        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
