<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Popuplogin
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div id="prpl-popuplogin" data-bind="scope:'prpl-popuplogin'" style="display: none">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<?php
    $socialLogin = null;
    if ($this->helper('Plumrocket\Base\Helper\Base')->moduleExists('SocialLoginPro') == 2) {
        $socialLogin = 'SocialLoginPro';
    } elseif ($this->helper('Plumrocket\Base\Helper\Base')->moduleExists('SocialLoginFree') == 2) {
        $socialLogin = 'SocialLoginFree';
    }
    $socialRegisterButtons = $socialLoginButtons = '';
    if ($socialLogin) {
        $helper = $this->helper("Plumrocket\\$socialLogin\Helper\Data");
        if($helper->modulePositionEnabled('login') && $helper->hasButtons()) {
            $socialRegisterButtons = $socialLoginButtons = '
                <div class="pslogin-spacer pslogin-clearfix">
                    <table>
                        <tr>
                            <td><div class="pslogin-border"></div></td>
                            <td class="pslogin-bordertext w25">'.__("OR").'</td>
                            <td><div class="pslogin-border"></div></td>
                        </tr>
                    </table>
                </div>';

            $socialLoginButtons .= $this->getLayout()
                ->createBlock("Plumrocket\\$socialLogin\Block\Buttons")
                ->setTemplate("Plumrocket_$socialLogin::customer/form/login/buttons.phtml")
                ->toHtml();

            $socialLoginButtons = str_replace(["\n", 'script'], ['', "scri'+'pt"], $this->escapeJsQuote($socialLoginButtons));

            $socialRegisterButtons .= $this->getLayout()
                ->createBlock("Plumrocket\\$socialLogin\Block\Buttons")
                ->setTemplate("Plumrocket_$socialLogin::customer/form/register/buttons.phtml")
                ->toHtml();

            $socialRegisterButtons = str_replace(["\n", 'script'], ['', "scri'+'pt"], $this->escapeJsQuote($socialRegisterButtons));
        }
    }
?>


<script type="text/javascript">
    window.socialLoginButtons = '<?php echo $socialLoginButtons; ?>';
    window.socialRegisterButtons = '<?php echo $socialRegisterButtons; ?>';
    if (window.socialLoginButtons) {
        require(['pslogin'], function(p){});
    }
    window.popupLoginConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
</script>

<script type="text/x-magento-init">
    {
        "#prpl-popuplogin": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>